import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  const translations = {
    en: {
      // Header
      search: 'Search...',
      calendar: 'Calendar',
      inbox: 'Inbox',
      notifications: 'Notifications',
      profile: 'Profile',
      logout: 'Log out',
      universityName: 'University of Quebec in Trois-Rivières (UQTR)',
      
      // Dashboard
      welcome: 'Welcome back',
      studentDashboard: 'Student Dashboard',
      haveProductiveDay: 'Have a productive day!',
      newTask: 'New Task',
      onlineCourse: 'Online Course',
      welcomeToUQTR: 'Welcome to UQTR',
      learningPlatform: 'Learning Platform',
      welcomeMessage: 'We\'re glad to see you here. Explore your courses, track your progress, and continue your professional development journey with us.',
      trainingCatalogue: 'Training Catalogue',
      selfRegistration: 'Self-Registration',
      progressTracking: 'Progress Tracking',
      multiFormatContent: 'Multi-Format Content',
      courseEnrollment: 'Course Enrollment',
      enrolled: 'Enrolled',
      completed: 'Completed',
      performance: 'Performance',
      myCourses: 'My Courses',
      viewAll: 'View All',
      todaysTask: 'Today\'s Task',
      newTask: 'New Task',
      all: 'All',
      open: 'Open',
      closed: 'Closed',
      archive: 'Archive',
      
      // Course details
      modules: 'modules',
      students: 'students',
      
      // Task details
      completeTrainingCatalogue: 'Complete Training Catalogue Setup',
      trainingCatalogueDescription: 'Configure course catalog for UQTR learners',
      reviewSelfRegistration: 'Review Self-Registration System',
      selfRegistrationDescription: 'Test and validate learner enrollment process',
      updateProgressReports: 'Update Progress Tracking Reports',
      progressReportsDescription: 'Generate monthly learning progress analytics',
      
      // Small stats
      integrationCapabilities: 'Integration Capabilities',
      ecommerceSupport: 'eCommerce Support',
      scormContent: 'SCORM Content',
      
      // Performance
      growthComparison: 'You have a 23% growth in comparison with last month.',
      
      // Calendar
      eventsFor: 'Events for',
      noEventsScheduled: 'No events scheduled',
      trainingCatalogueSetup: 'Training Catalogue Setup',
      selfRegistrationTraining: 'Self-Registration System Training',
      progressTrackingWorkshop: 'Progress Tracking Workshop',
      scormContentIntegration: 'SCORM Content Integration',
      ecommerceSupportTraining: 'eCommerce Support Training',
      integrationCapabilitiesWorkshop: 'Integration Capabilities Workshop',
      multiFormatContentTraining: 'Multi-Format Content Training',
      customizedCurriculum: 'Customized Curriculum & Scenario Design',
      assessmentWorkshop: 'Assessment & Evaluation Workshop',
      finalCertificationAssessment: 'Final Certification Assessment',
      module: 'module',
      workshop: 'workshop',
      
      // Months
      january: 'January',
      february: 'February',
      march: 'March',
      april: 'April',
      may: 'May',
      june: 'June',
      july: 'July',
      august: 'August',
      september: 'September',
      october: 'October',
      november: 'November',
      december: 'December',
      
      // Announcements
      announcements: 'Announcements',
      newTrainingCatalogueModule: 'New UQTR Training Catalogue Module Available',
      uqtrTrainingCoordinator: 'UQTR Training Coordinator',
      newTrainingCatalogueContent: 'Advanced UQTR Training Catalogue Module 2: Self-Registration & Progress Tracking is now available for enrollment.',
      scormIntegrationWorkshop: 'SCORM Content Integration Workshop',
      uqtrContentDepartment: 'UQTR Content Department',
      scormIntegrationContent: 'Join our upcoming workshop on SCORM 1.2/2004 content integration and multi-format support.',
      progressTrackingSurvey: 'Progress Tracking Analytics Survey',
      uqtrAnalyticsTeam: 'UQTR Analytics Team',
      progressTrackingSurveyContent: 'Please complete the progress tracking effectiveness survey to help us improve our analytics and reporting systems.',
      trainingManagement: 'Training Management',
      contentManagement: 'Content Management',
      analytics: 'Analytics',
      noAnnouncements: 'No announcements',
      checkBackLater: 'Check back later for updates',
      weekAgo: '1 week ago',
      hoursAgo: '2 hours ago',
      high: 'High',
      daysAgo: '5 days ago',
      
      // Zoom Classes
      zoomClassesManagement: 'Zoom Classes Management',
      upcomingClasses: 'Upcoming Classes',
      completedClasses: 'Completed Classes',
      noUpcomingClasses: 'No upcoming classes scheduled',
      scheduleFirstClass: 'Schedule your first class to get started',
      noCompletedClasses: 'No completed classes yet',
      completeFirstClass: 'Complete your first class to see it here',
      instructor: 'Instructor',
      joinViaZoom: 'Join via Zoom',
      viewRecording: 'View Recording',
      download: 'Download',
      completed: 'Completed',
      editClass: 'Edit Class',
      updateClass: 'Update Class',
      cancel: 'Cancel',
      recording: 'Recording',
      recordingPlayer: 'Recording Player',
      classHeldOn: 'Class held on',
      attendance: 'Attendance',
      students: 'students',
      downloadRecording: 'Download Recording',
      
      // Sidebar Navigation
      home: 'Home',
      courses: 'Courses',
      communityResources: 'Community Resources',
      catalog: 'Catalog',
      messages: 'Messages',
      games: 'Games',
      events: 'Events',
      evaluationFeedback: 'Evaluation & Feedback',
      helpSupport: 'Help & Support',
      adminPortal: 'Admin Portal',
      faqs: 'FAQs',
      contactSupport: 'Contact Support',
      userGuides: 'User Guides',
      supportTicket: 'Support Ticket',

      // Admin Portal
      overview: 'Overview',
      uploadCourses: 'Upload Courses',
      webinars: 'Webinars',
      schedule: 'Schedule',
      users: 'Users',
      reports: 'Reports',
      feedbackReports: 'Feedback Reports',
      overviewSummary: 'Overview Summary',
      dashboardAnalytics: 'Dashboard analytics and key metrics',
      totalUsers: 'Total Users',
      thisMonth: 'this month',
      platformActivity: 'Platform Activity',
      courseCompletions: 'Course Completions',
      activeSessions: 'Active Sessions',
      newRegistrations: 'New Registrations',
      supportTickets: 'Support Tickets',
      recentActivity: 'Recent Activity',
      newCourseUploaded: 'New course "Advanced Training" uploaded',
      webinarScheduled: 'Webinar "Safety Protocols" scheduled',
      monthlyReportGenerated: 'Monthly report generated',
      newUsersRegistered: '15 new users registered',
      hoursAgo: '2 hours ago',

      // Catalog & Groups
      trainingCatalog: 'Training Catalog',
      trainingCatalogDescription: 'Explore our comprehensive collection of UQTR training programs',
      searchPlaceholder: 'Search by name, description, or tags...',
      courses: 'Courses',
      exploreCatalog: 'Explore Catalog',
      noResultsFound: 'No Results Found',
      noResultsDescription: 'We couldn\'t find any catalogs matching your search. Try adjusting your search terms.',
      uqtrTrainingCatalogue: 'UQTR Training Catalogue',
      uqtrTrainingDescription: 'Comprehensive training management and course catalog system',
      uqtrSelfRegistration: 'UQTR Self-Registration',
      uqtrSelfRegistrationDescription: 'Automated learner enrollment and registration system',
      uqtrProgressTracking: 'UQTR Progress Tracking',
      uqtrProgressTrackingDescription: 'Advanced analytics and progress monitoring tools',
      weeks: '12 weeks',
      intermediate: 'Intermediate',
      beginner: 'Beginner',
      advanced: 'Advanced',
      systemAdministration: 'System Administration',
      userManagement: 'User Management',
      enrollment: 'Enrollment',
      reporting: 'Reporting',
      dataVisualization: 'Data Visualization',
      myCommunityResources: 'My Community Resources',
      communityResourcesDescription: 'Manage and participate in your enrolled community resources',
      discoverGroups: 'Discover Groups',
      searchMyGroups: 'Search my groups...',
      allTypes: 'All types',
      interestGroups: 'Interest groups',
      studyGroups: 'Study groups',
      businessGroups: 'Business groups',
      members: 'Members',
      openGroup: 'Open Group',
      enrolled: 'Enrolled',
      professionalTraining: 'Professional Training',
      communityDevelopment: 'Community Development',
      legalEducation: 'Legal Education',
      researchGroup: 'Research Group',
      studentOrganization: 'Student Organization',
      
      // Group Detail Page
      active: 'Active',
      trainingSessions: 'Training Sessions',
      certifications: 'Certifications',
      groupInformation: 'Group Information',
      category: 'Category',
      createdDate: 'Created Date',
      lastActivity: 'Last Activity',
      status: 'Status',
      totalMembers: 'Total Members',
      groupType: 'Group Type',
      recentActivity: 'Recent Activity',
      newTrainingSession: 'New training session: "Stakeholder Analysis & Needs Assessment"',
      newMembersJoined: '5 new officers joined the training program',
      certificationExamScheduled: 'Module 2 certification exam scheduled for next week',
      trainingMaterialsUpdated: 'DOJ compliance training materials updated',
      oneHourAgo: '1 hour ago',
      twoDaysAgo: '2 days ago',
      fourDaysAgo: '4 days ago',
      oneWeekAgo: '1 week ago',
      
      // UQTR Group Names
      uqtrLawEnforcementTraining: 'UQTR Law Enforcement Training Group',
      uqtrCommunityOutreach: 'UQTR Community Outreach Program',
      uqtrLegalTrainingSpecialists: 'UQTR Legal Training Specialists',
      
      // UQTR Group Descriptions
      uqtrLawEnforcementDescription: 'DOJ Law Enforcement Training Group focused on professional development, stakeholder analysis, and advanced law enforcement skills enhancement',
      uqtrCommunityOutreachDescription: 'Community development program focused on building partnerships, fostering community engagement, and promoting social development initiatives',
      uqtrLegalTrainingDescription: 'Legal education specialists group focused on advanced legal training, case studies, and professional development for legal professionals',
      
      // Group Categories
      lawEnforcementTraining: 'Law Enforcement Training',
      communityDevelopment: 'Community Development',
      legalEducation: 'Legal Education',
      
      // Group Status
      activeAcceptingTrainees: 'Active and accepting new trainees',
      activeAcceptingMembers: 'Active and accepting new members',
      activeAcceptingStudents: 'Active and accepting new students',
      
      // Dates
      january152024: 'January 15, 2024',
      february102024: 'February 10, 2024',
      march52024: 'March 5, 2024',
      
      // Time References
      oneHourAgo: '1 hour ago',
      twoHoursAgo: '2 hours ago',
      threeHoursAgo: '3 hours ago',
      
      // Member Counts
      fortyFiveOfficers: '45 officers',
      thirtyTwoMembers: '32 members',
      twentyEightStudents: '28 students',
      
      // Group Types
      professionalTrainingGroup: 'Professional Training Group',
      communityDevelopmentGroup: 'Community Development Group',
      legalEducationGroup: 'Legal Education Group',

      // Messages
      searchContacts: 'Search contacts...',
      newChat: 'New Chat',
      selectContact: 'Select Contact',
      searchUsers: 'Search users...',
      noUsersFound: 'No users found',
      voiceMessage: 'Voice message',
      pdfDocument: 'PDF Document',
      addImages: 'Add Images',
      addFiles: 'Add Files',
      typeMessage: 'Type a message...',
      emojis: 'Emojis',
      selectConversation: 'Select a conversation to start messaging',
      selectConversationDescription: 'Choose from your existing conversations or start a new one to connect with your learning community',

      // Contact Names
      sarahWilson: 'Sarah Wilson',
      michaelChen: 'Michael Chen',
      emilyBrown: 'Emily Brown',
      davidKim: 'David Kim',
      jessicaTaylor: 'Jessica Taylor',
      robertJohnson: 'Robert Johnson',

      // Contact Messages
      heyThere: 'Hey there!',
      letsCatchUpLater: 'Let\'s catch up later',
      didYouSeeNewCourse: 'Did you see the new course?',
      thanksForHelp: 'Thanks for your help!',
      areYouFreeTomorrow: 'Are you free tomorrow?',
      illGetBackToYou: 'I\'ll get back to you',

      // Sample Chat Messages
      hiHowAreYou: 'Hi! How are you?',
      imDoingGreat: 'I\'m doing great! Just finished the React module.',
      thatsAwesome: 'That\'s awesome! I\'m still working on it.',
      letMeKnowIfYouNeedHelp: 'Let me know if you need any help with it.',

      // Time References
      yesterday: 'Yesterday',
      twoDaysAgo: '2 days ago',

      // Events
      uqtrTrainingWorkshop: 'UQTR Training Workshop',
      uqtrCommunityOutreach: 'UQTR Community Outreach',
      uqtrPolicyRoundtable: 'UQTR Policy Roundtable',
      online: 'Online',
      troisRivieres: 'Trois-Rivières, QC',
      uqtrCampus: 'UQTR Campus',
      webinar: 'Webinar',
      outreach: 'Outreach',
      meeting: 'Meeting',
      discoverAndRsvp: 'Discover and RSVP to upcoming events.',
      myRsvps: 'My RSVPs',
      searchByTitleOrLocation: 'Search by title or location...',
      filterByType: 'Filter by type',
      reset: 'Reset',
      upcomingThisMonth: 'Upcoming this month',
      totalRsvps: 'Total RSVPs',
      avgCapacityUsed: 'Avg. capacity used',
      viewUpcomingEvents: 'View upcoming events in a monthly view.',
      openCalendar: 'Open Calendar',
      seeEventsResponded: 'See events you\'ve responded to.',
      viewRsvps: 'View RSVPs',
      subscribe: 'Subscribe',
      getEventReminders: 'Get event reminders and updates.',
      unsubscribe: 'Unsubscribe',
      upcomingEvents: 'Upcoming events',
      results: 'result(s)',
      attending: 'attending',
      updateRsvp: 'Update RSVP',
      rsvp: 'RSVP',
      rsvpTo: 'RSVP to',
      interested: 'Interested',
      notGoing: 'Not Going',
      cancel: 'Cancel',
      confirm: 'Confirm',
      saved: 'Saved',
      save: 'Save',
      addToCalendar: 'Add to Calendar',
      share: 'Share',
      youHave: 'You have',
      savedEvent: 'saved event',
      subscribed: 'Subscribed',
      unsubscribed: 'Unsubscribed',
      willReceiveReminders: 'You will receive reminders for upcoming events.',
      willNotReceiveReminders: 'You will no longer receive reminders.',
      rsvpUpdated: 'RSVP updated',
      for: 'for',
      addedToCalendar: 'Added to calendar',
      icsFileDownloaded: 'ICS file downloaded.',
      shareLinkCopied: 'Share link copied',
      linkFor: 'Link for',
      copiedToClipboard: 'copied to clipboard.',

      // Evaluation & Feedback
      evaluationFeedback: 'Evaluation & Feedback',
      monitorLearningProgress: 'Monitor your learning progress and training effectiveness.',
      postTrainingSurveys: 'Post-Training Surveys',
      shareTrainingExperience: 'Share your training experience',
      takeSurvey: 'Take Survey',
      selfAssessment: 'Self-Assessment',
      evaluateSkillsProgress: 'Evaluate your skills and progress',
      startAssessment: 'Start Assessment',
      surveyCompletion: 'Survey Completion',
      averageRating: 'Average Rating',
      totalResponses: 'Total Responses',
      overallScore: 'Overall Score',
      skillAssessment: 'Skill Assessment',
      recentFeedback: 'Recent Feedback',
      excellentCourseContent: 'Excellent course content and practical examples.',
      veryHelpfulUnderstanding: 'Very helpful for understanding student needs.',
      outstandingProgramRealWorld: 'Outstanding program with real-world applications.',
      communicationSkills: 'Communication Skills',
      technicalKnowledge: 'Technical Knowledge',
      leadershipSkills: 'Leadership Skills',
      problemSolving: 'Problem Solving',

      // Help & Support
      frequentlyAskedQuestions: 'Frequently Asked Questions',
      findAnswersCommonQuestions: 'Find answers to common questions about our platform',
      generalQuestions: 'General Questions',
      howToResetPassword: 'How do I reset my password?',
      resetPasswordAnswer: 'To reset your password, click on the "Forgot Password" link on the login page and follow the instructions sent to your email.',
      howToUpdateProfile: 'How do I update my profile information?',
      updateProfileAnswer: 'You can update your profile information by clicking on your profile picture in the top right corner and selecting "Edit Profile".',
      systemRequirements: 'What are the system requirements?',
      systemRequirementsAnswer: 'Our platform works best on the latest versions of Chrome, Firefox, Safari, and Edge. Make sure you have JavaScript enabled.',
      howToContactSupport: 'How do I contact support?',
      contactSupportAnswer: 'You can contact our support team through the Contact Support page or by emailing support@uqtr.ca',
      mobileAppAvailable: 'Is there a mobile app available?',
      mobileAppAnswer: 'Yes, our mobile app is available for both iOS and Android devices. You can download it from the App Store or Google Play Store.',
      wereHereToHelp: 'We\'re here to help! Reach out to our support team for assistance.',
      contactInformation: 'Contact Information',
      emailUs: 'Email Us',
      callUs: 'Call Us',
      workingHours: 'Working Hours',
      mondayFridayHours: 'Monday - Friday: 9:00 AM - 6:00 PM',
      sendUsMessage: 'Send us a Message',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      emailPlaceholder: 'john@uqtr.ca',
      subjectPlaceholder: 'What\'s this about?',
      messagePlaceholder: 'How can we help you?',
      sendMessage: 'Send Message',
      resetPasswordSimpleAnswer: 'You can reset your password by clicking on "Forgot Password" on the login page.',
      updateProfileSimpleAnswer: 'Navigate to your profile settings to update your personal information.',
      userGuidesDocumentation: 'User Guides & Documentation',
      findHelpfulGuides: 'Find helpful guides, tutorials, and documentation to get the most out of our platform.',
      gettingStartedGuide: 'Getting Started Guide',
      gettingStartedDescription: 'Learn how to set up your account and navigate the platform with our comprehensive guide.',
      videoTutorials: 'Video Tutorials',
      videoTutorialsDescription: 'Watch step-by-step video tutorials to master all the features of our platform.',
      apiDocumentation: 'API Documentation',
      apiDocumentationDescription: 'Technical documentation for integrating with our API and building custom solutions.',
      keyboardShortcuts: 'Keyboard Shortcuts',
      keyboardShortcutsDescription: 'Boost your productivity with these handy keyboard shortcuts for common actions.',
      videoSeries: 'Video Series',
      web: 'Web',
      cheatSheet: 'Cheat Sheet',
      allGuides: 'All Guides',
      gettingStarted: 'Getting Started',
      features: 'Features',
      troubleshooting: 'Troubleshooting',
      viewGuide: 'View Guide',
      lastUpdated: 'Last updated',
      cantFindWhatLookingFor: 'Can\'t find what you\'re looking for?',
      supportTeamReadyToHelp: 'Our support team is always ready to help with any questions you might have.',
      createSupportTicket: 'Create Support Ticket',
      fillOutFormSubmitTicket: 'Fill out the form below to submit a support ticket to our team.',
      newSupportTicket: 'New Support Ticket',
      brieflyDescribeIssue: 'Briefly describe your issue',
      selectPriority: 'Select priority',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      selectCategory: 'Select category',
      technicalIssue: 'Technical Issue',
      billing: 'Billing',
      account: 'Account',
      featureRequest: 'Feature Request',
      other: 'Other',
      provideDetailedInformation: 'Please provide detailed information about your issue',
      attachments: 'Attachments',
      addFiles: 'Add Files',
      filesAttached: 'file(s) attached',
      submitTicket: 'Submit Ticket',

      // Task Management
      taskManagement: 'Task Management',
      organizeTrackTasksEfficiently: 'Organize and track your tasks efficiently',
      backToHome: 'Back to Home',
      addNewTask: 'Add New Task',
      createNewTask: 'Create New Task',
      editTask: 'Edit Task',
      taskTitle: 'Task title',
      taskDescription: 'Task description',
      deadline: 'Deadline',
      deadlinePlaceholder: 'Deadline (e.g., Today, Tomorrow, Next week)',
      priority: 'Priority',
      status: 'Status',
      category: 'Category',
      addTask: 'Add Task',
      updateTask: 'Update Task',
      cancel: 'Cancel',
      allTasks: 'All Tasks',
      pleaseFillRequiredFields: 'Please fill in all required fields',
      taskAddedSuccessfully: 'Task added successfully',
      taskUpdatedSuccessfully: 'Task updated successfully',
      taskDeletedSuccessfully: 'Task deleted successfully',
      taskMarkedAsPending: 'Task marked as pending',
      taskCompleted: 'Task completed',
      highPriority: 'High Priority',
      mediumPriority: 'Medium Priority',
      lowPriority: 'Low Priority',
      pending: 'Pending',
      inprogress: 'In Progress',
      completed: 'Completed',
      courseDevelopment: 'Course Development',
      assessment: 'Assessment',
      contentUpdates: 'Content Updates',
      administration: 'Administration',
      compliance: 'Compliance',
      trainingDelivery: 'Training Delivery',
      today: 'Today',
      tomorrow: 'Tomorrow',
      nextWeek: 'Next week',
      inTwoWeeks: 'In 2 weeks',
      nextMonth: 'Next month',
      thisFriday: 'This Friday',
      reviewUQTRTrainingCatalogue: 'Review UQTR Training Catalogue Content',
      reviewUQTRTrainingCatalogueDescription: 'Review and update UQTR Training Catalogue content for accuracy and compliance with university standards',
      gradeUQTRSelfRegistration: 'Grade UQTR Self-Registration Assessments',
      gradeUQTRSelfRegistrationDescription: 'Evaluate recent UQTR Self-Registration system assessments and provide detailed feedback to participants',
      prepareUQTRProgressTracking: 'Prepare UQTR Progress Tracking Exam',
      prepareUQTRProgressTrackingDescription: 'Create comprehensive exam questions for UQTR Progress Tracking Module final assessment',
      updateUQTRComplianceMaterials: 'Update UQTR Compliance Training Materials',
      updateUQTRComplianceMaterialsDescription: 'Update UQTR compliance training materials with latest university regulatory requirements',
      scheduleUQTRInstructorSessions: 'Schedule UQTR Instructor Sessions',
      scheduleUQTRInstructorSessionsDescription: 'Set up training schedule for UQTR faculty, education, and student development instructors',
      reviewUQTRStakeholderAnalysis: 'Review UQTR Stakeholder Analysis Module',
      reviewUQTRStakeholderAnalysisDescription: 'Final review of UQTR Stakeholder Analysis & Needs Assessment module content before publication',

      // Today's Task Section
      todaysTask: 'Today\'s Task',
      newTask: 'New Task',
      viewAllTasks: 'View All Tasks',
      all: 'All',
      open: 'Open',
      closed: 'Closed',
      archived: 'Archived',
      completeUQTRTrainingCatalogue: 'Complete UQTR Training Catalogue',
      completeUQTRTrainingCatalogueDescription: 'Foundations of UQTR Training Catalogue System',
      reviewUQTRSelfRegistration: 'Review UQTR Self-Registration',
      reviewUQTRSelfRegistrationDescription: 'Professional Learning in UQTR Self-Registration',
      submitUQTRProgressTracking: 'Submit UQTR Progress Tracking',
      submitUQTRProgressTrackingDescription: 'Needs Assessment in UQTR Progress Tracking',

      // My Courses Section
      myCourses: 'My Courses',
      viewAll: 'View All',
      modules: 'modules',
      students: 'students',
      uqtrUniversity: 'UQTR University',
      buildingExcellenceFosteringGrowth: 'Building Excellence, Fostering Growth',
      progress: 'Progress'
    },
    fr: {
      // Header
      search: 'Rechercher...',
      calendar: 'Calendrier',
      inbox: 'Boîte de réception',
      notifications: 'Notifications',
      profile: 'Profil',
      logout: 'Se déconnecter',
      universityName: 'University of Quebec in Trois-Rivières (UQTR)',
      
      // Dashboard
      welcome: 'Bon retour',
      studentDashboard: 'Tableau de bord étudiant',
      haveProductiveDay: 'Passez une journée productive !',
      newTask: 'Nouvelle tâche',
      onlineCourse: 'Cours en ligne',
      welcomeToUQTR: 'Bienvenue à l\'UQTR',
      learningPlatform: 'Plateforme d\'apprentissage',
      welcomeMessage: 'Nous sommes heureux de vous voir ici. Explorez vos cours, suivez vos progrès et continuez votre parcours de développement professionnel avec nous.',
      trainingCatalogue: 'Catalogue de formation',
      selfRegistration: 'Auto-inscription',
      progressTracking: 'Suivi des progrès',
      multiFormatContent: 'Contenu multi-format',
      courseEnrollment: 'Inscription aux cours',
      enrolled: 'Inscrit',
      completed: 'Terminé',
      performance: 'Performance',
      myCourses: 'Mes cours',
      viewAll: 'Voir tout',
      todaysTask: 'Tâche d\'aujourd\'hui',
      newTask: 'Nouvelle tâche',
      all: 'Tout',
      open: 'Ouvert',
      closed: 'Fermé',
      archive: 'Archives',
      
      // Course details
      modules: 'modules',
      students: 'étudiants',
      
      // Task details
      completeTrainingCatalogue: 'Compléter la configuration du catalogue de formation',
      trainingCatalogueDescription: 'Configurer le catalogue de cours pour les apprenants UQTR',
      reviewSelfRegistration: 'Examiner le système d\'auto-inscription',
      selfRegistrationDescription: 'Tester et valider le processus d\'inscription des apprenants',
      updateProgressReports: 'Mettre à jour les rapports de suivi des progrès',
      progressReportsDescription: 'Générer les analyses mensuelles des progrès d\'apprentissage',
      
      // Small stats
      integrationCapabilities: 'Capacités d\'intégration',
      ecommerceSupport: 'Support eCommerce',
      scormContent: 'Contenu SCORM',
      
      // Performance
      growthComparison: 'Vous avez une croissance de 23% par rapport au mois dernier.',
      
      // Calendar
      eventsFor: 'Événements pour le',
      noEventsScheduled: 'Aucun événement programmé',
      trainingCatalogueSetup: 'Configuration du catalogue de formation',
      selfRegistrationTraining: 'Formation au système d\'auto-inscription',
      progressTrackingWorkshop: 'Atelier de suivi des progrès',
      scormContentIntegration: 'Intégration de contenu SCORM',
      ecommerceSupportTraining: 'Formation au support eCommerce',
      integrationCapabilitiesWorkshop: 'Atelier sur les capacités d\'intégration',
      multiFormatContentTraining: 'Formation au contenu multi-format',
      customizedCurriculum: 'Conception de programme et de scénario personnalisé',
      assessmentWorkshop: 'Atelier d\'évaluation et d\'évaluation',
      finalCertificationAssessment: 'Évaluation de certification finale',
      module: 'module',
      workshop: 'atelier',
      
      // Months
      january: 'Janvier',
      february: 'Février',
      march: 'Mars',
      april: 'Avril',
      may: 'Mai',
      june: 'Juin',
      july: 'Juillet',
      august: 'Août',
      september: 'Septembre',
      october: 'Octobre',
      november: 'Novembre',
      december: 'Décembre',
      
      // Announcements
      announcements: 'Annonces',
      newTrainingCatalogueModule: 'Nouveau module de catalogue de formation UQTR disponible',
      uqtrTrainingCoordinator: 'Coordinateur de formation UQTR',
      newTrainingCatalogueContent: 'Module avancé de catalogue de formation UQTR 2: Auto-inscription et suivi des progrès est maintenant disponible pour inscription.',
      scormIntegrationWorkshop: 'Atelier d\'intégration de contenu SCORM',
      uqtrContentDepartment: 'Département de contenu UQTR',
      scormIntegrationContent: 'Rejoignez notre prochain atelier sur l\'intégration de contenu SCORM 1.2/2004 et le support multi-format.',
      progressTrackingSurvey: 'Enquête sur les analyses de suivi des progrès',
      uqtrAnalyticsTeam: 'Équipe d\'analyses UQTR',
      progressTrackingSurveyContent: 'Veuillez compléter l\'enquête sur l\'efficacité du suivi des progrès pour nous aider à améliorer nos systèmes d\'analyses et de rapports.',
      trainingManagement: 'Gestion de formation',
      contentManagement: 'Gestion de contenu',
      analytics: 'Analyses',
      noAnnouncements: 'Aucune annonce',
      checkBackLater: 'Revenez plus tard pour les mises à jour',
      weekAgo: 'il y a 1 semaine',
      hoursAgo: 'il y a 2 heures',
      high: 'Élevé',
      daysAgo: 'il y a 5 jours',
      
      // Zoom Classes
      zoomClassesManagement: 'Gestion des classes Zoom',
      upcomingClasses: 'Classes à venir',
      completedClasses: 'Classes terminées',
      noUpcomingClasses: 'Aucune classe à venir programmée',
      scheduleFirstClass: 'Programmez votre première classe pour commencer',
      noCompletedClasses: 'Aucune classe terminée pour le moment',
      completeFirstClass: 'Terminez votre première classe pour la voir ici',
      instructor: 'Instructeur',
      joinViaZoom: 'Rejoindre via Zoom',
      viewRecording: 'Voir l\'enregistrement',
      download: 'Télécharger',
      completed: 'Terminé',
      editClass: 'Modifier la classe',
      updateClass: 'Mettre à jour la classe',
      cancel: 'Annuler',
      recording: 'Enregistrement',
      recordingPlayer: 'Lecteur d\'enregistrement',
      classHeldOn: 'Classe tenue le',
      attendance: 'Présence',
      students: 'étudiants',
      downloadRecording: 'Télécharger l\'enregistrement',
      
      // Sidebar Navigation
      home: 'Accueil',
      courses: 'Cours',
      communityResources: 'Ressources communautaires',
      catalog: 'Catalogue',
      messages: 'Messages',
      games: 'Jeux',
      events: 'Événements',
      evaluationFeedback: 'Évaluation et commentaires',
      helpSupport: 'Aide et support',
      adminPortal: 'Portail administrateur',
      faqs: 'FAQ',
      contactSupport: 'Contacter le support',
      userGuides: 'Guides utilisateur',
      supportTicket: 'Ticket de support',

      // Admin Portal
      overview: 'Aperçu',
      uploadCourses: 'Télécharger des cours',
      webinars: 'Webinaires',
      schedule: 'Planification',
      users: 'Utilisateurs',
      reports: 'Rapports',
      feedbackReports: 'Rapports de commentaires',
      overviewSummary: 'Résumé de l\'aperçu',
      dashboardAnalytics: 'Analyses du tableau de bord et métriques clés',
      totalUsers: 'Total des utilisateurs',
      thisMonth: 'ce mois-ci',
      platformActivity: 'Activité de la plateforme',
      courseCompletions: 'Achèvements de cours',
      activeSessions: 'Sessions actives',
      newRegistrations: 'Nouvelles inscriptions',
      supportTickets: 'Tickets de support',
      recentActivity: 'Activité récente',
      newCourseUploaded: 'Nouveau cours "Formation avancée" téléchargé',
      webinarScheduled: 'Webinaire "Protocoles de sécurité" programmé',
      monthlyReportGenerated: 'Rapport mensuel généré',
      newUsersRegistered: '15 nouveaux utilisateurs inscrits',
      hoursAgo: 'il y a 2 heures',

      // Catalog & Groups
      trainingCatalog: 'Catalogue de formation',
      trainingCatalogDescription: 'Explorez notre collection complète de programmes de formation UQTR',
      searchPlaceholder: 'Rechercher par nom, description ou étiquettes...',
      courses: 'Cours',
      exploreCatalog: 'Explorer le catalogue',
      noResultsFound: 'Aucun résultat trouvé',
      noResultsDescription: 'Nous n\'avons trouvé aucun catalogue correspondant à votre recherche. Essayez d\'ajuster vos termes de recherche.',
      uqtrTrainingCatalogue: 'Catalogue de formation UQTR',
      uqtrTrainingDescription: 'Système complet de gestion de formation et de catalogue de cours',
      uqtrSelfRegistration: 'Auto-inscription UQTR',
      uqtrSelfRegistrationDescription: 'Système automatisé d\'inscription et d\'enregistrement des apprenants',
      uqtrProgressTracking: 'Suivi des progrès UQTR',
      uqtrProgressTrackingDescription: 'Outils avancés d\'analyses et de suivi des progrès',
      weeks: '12 semaines',
      intermediate: 'Intermédiaire',
      beginner: 'Débutant',
      advanced: 'Avancé',
      systemAdministration: 'Administration système',
      userManagement: 'Gestion des utilisateurs',
      enrollment: 'Inscription',
      reporting: 'Rapports',
      dataVisualization: 'Visualisation des données',
      myCommunityResources: 'Mes ressources communautaires',
      communityResourcesDescription: 'Gérez et participez à vos ressources communautaires inscrites',
      discoverGroups: 'Découvrir les groupes',
      searchMyGroups: 'Rechercher mes groupes...',
      allTypes: 'Tous les types',
      interestGroups: 'Groupes d\'intérêt',
      studyGroups: 'Groupes d\'étude',
      businessGroups: 'Groupes d\'affaires',
      members: 'Membres',
      openGroup: 'Ouvrir le groupe',
      enrolled: 'Inscrit',
      professionalTraining: 'Formation professionnelle',
      communityDevelopment: 'Développement communautaire',
      legalEducation: 'Éducation juridique',
      researchGroup: 'Groupe de recherche',
      studentOrganization: 'Organisation étudiante',
      
      // Group Detail Page
      active: 'Actif',
      trainingSessions: 'Sessions de formation',
      certifications: 'Certifications',
      groupInformation: 'Informations du groupe',
      category: 'Catégorie',
      createdDate: 'Date de création',
      lastActivity: 'Dernière activité',
      status: 'Statut',
      totalMembers: 'Total des membres',
      groupType: 'Type de groupe',
      recentActivity: 'Activité récente',
      newTrainingSession: 'Nouvelle session de formation : "Analyse des parties prenantes et évaluation des besoins"',
      newMembersJoined: '5 nouveaux officiers ont rejoint le programme de formation',
      certificationExamScheduled: 'Examen de certification du module 2 programmé pour la semaine prochaine',
      trainingMaterialsUpdated: 'Matériel de formation de conformité DOJ mis à jour',
      oneHourAgo: 'Il y a 1 heure',
      twoDaysAgo: 'Il y a 2 jours',
      fourDaysAgo: 'Il y a 4 jours',
      oneWeekAgo: 'Il y a 1 semaine',
      
      // UQTR Group Names
      uqtrLawEnforcementTraining: 'Groupe de formation en application de la loi UQTR',
      uqtrCommunityOutreach: 'Programme de sensibilisation communautaire UQTR',
      uqtrLegalTrainingSpecialists: 'Spécialistes en formation juridique UQTR',
      
      // UQTR Group Descriptions
      uqtrLawEnforcementDescription: 'Groupe de formation en application de la loi DOJ axé sur le développement professionnel, l\'analyse des parties prenantes et l\'amélioration des compétences avancées en application de la loi',
      uqtrCommunityOutreachDescription: 'Programme de développement communautaire axé sur la construction de partenariats, la promotion de l\'engagement communautaire et l\'initiative de développement social',
      uqtrLegalTrainingDescription: 'Groupe de spécialistes en éducation juridique axé sur la formation juridique avancée, les études de cas et le développement professionnel pour les professionnels du droit',
      
      // Group Categories
      lawEnforcementTraining: 'Formation en application de la loi',
      communityDevelopment: 'Développement communautaire',
      legalEducation: 'Éducation juridique',
      
      // Group Status
      activeAcceptingTrainees: 'Actif et acceptant de nouveaux stagiaires',
      activeAcceptingMembers: 'Actif et acceptant de nouveaux membres',
      activeAcceptingStudents: 'Actif et acceptant de nouveaux étudiants',
      
      // Dates
      january152024: '15 janvier 2024',
      february102024: '10 février 2024',
      march52024: '5 mars 2024',
      
      // Time References
      oneHourAgo: 'Il y a 1 heure',
      twoHoursAgo: 'Il y a 2 heures',
      threeHoursAgo: 'Il y a 3 heures',
      
      // Member Counts
      fortyFiveOfficers: '45 officiers',
      thirtyTwoMembers: '32 membres',
      twentyEightStudents: '28 étudiants',
      
      // Group Types
      professionalTrainingGroup: 'Groupe de formation professionnelle',
      communityDevelopmentGroup: 'Groupe de développement communautaire',
      legalEducationGroup: 'Groupe d\'éducation juridique',

      // Messages
      searchContacts: 'Rechercher des contacts...',
      newChat: 'Nouveau chat',
      selectContact: 'Sélectionner un contact',
      searchUsers: 'Rechercher des utilisateurs...',
      noUsersFound: 'Aucun utilisateur trouvé',
      voiceMessage: 'Message vocal',
      pdfDocument: 'Document PDF',
      addImages: 'Ajouter des images',
      addFiles: 'Ajouter des fichiers',
      typeMessage: 'Tapez un message...',
      emojis: 'Emojis',
      selectConversation: 'Sélectionnez une conversation pour commencer à envoyer des messages',
      selectConversationDescription: 'Choisissez parmi vos conversations existantes ou commencez-en une nouvelle pour vous connecter avec votre communauté d\'apprentissage',

      // Contact Names
      sarahWilson: 'Sarah Wilson',
      michaelChen: 'Michael Chen',
      emilyBrown: 'Emily Brown',
      davidKim: 'David Kim',
      jessicaTaylor: 'Jessica Taylor',
      robertJohnson: 'Robert Johnson',

      // Contact Messages
      heyThere: 'Salut !',
      letsCatchUpLater: 'Rattrapons-nous plus tard',
      didYouSeeNewCourse: 'As-tu vu le nouveau cours ?',
      thanksForHelp: 'Merci pour ton aide !',
      areYouFreeTomorrow: 'Es-tu libre demain ?',
      illGetBackToYou: 'Je te recontacte',

      // Sample Chat Messages
      hiHowAreYou: 'Salut ! Comment vas-tu ?',
      imDoingGreat: 'Je vais très bien ! Je viens de terminer le module React.',
      thatsAwesome: 'C\'est génial ! Je travaille encore dessus.',
      letMeKnowIfYouNeedHelp: 'Fais-moi savoir si tu as besoin d\'aide.',

      // Time References
      yesterday: 'Hier',
      twoDaysAgo: 'Il y a 2 jours',

      // Events
      uqtrTrainingWorkshop: 'Atelier de formation UQTR',
      uqtrCommunityOutreach: 'Outreach communautaire UQTR',
      uqtrPolicyRoundtable: 'Table ronde politique UQTR',
      online: 'En ligne',
      troisRivieres: 'Trois-Rivières, QC',
      uqtrCampus: 'Campus UQTR',
      webinar: 'Webinaire',
      outreach: 'Outreach',
      meeting: 'Réunion',
      discoverAndRsvp: 'Découvrez et répondez aux événements à venir.',
      myRsvps: 'Mes RSVP',
      searchByTitleOrLocation: 'Rechercher par titre ou lieu...',
      filterByType: 'Filtrer par type',
      reset: 'Réinitialiser',
      upcomingThisMonth: 'À venir ce mois-ci',
      totalRsvps: 'Total des RSVP',
      avgCapacityUsed: 'Capacité moyenne utilisée',
      viewUpcomingEvents: 'Voir les événements à venir en vue mensuelle.',
      openCalendar: 'Ouvrir le calendrier',
      seeEventsResponded: 'Voir les événements auxquels vous avez répondu.',
      viewRsvps: 'Voir les RSVP',
      subscribe: 'S\'abonner',
      getEventReminders: 'Recevez des rappels et des mises à jour d\'événements.',
      unsubscribe: 'Se désabonner',
      upcomingEvents: 'Événements à venir',
      results: 'résultat(s)',
      attending: 'participants',
      updateRsvp: 'Mettre à jour RSVP',
      rsvp: 'RSVP',
      rsvpTo: 'RSVP pour',
      interested: 'Intéressé',
      notGoing: 'Ne participe pas',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      saved: 'Enregistré',
      save: 'Enregistrer',
      addToCalendar: 'Ajouter au calendrier',
      share: 'Partager',
      youHave: 'Vous avez',
      savedEvent: 'événement enregistré',
      subscribed: 'Abonné',
      unsubscribed: 'Désabonné',
      willReceiveReminders: 'Vous recevrez des rappels pour les événements à venir.',
      willNotReceiveReminders: 'Vous ne recevrez plus de rappels.',
      rsvpUpdated: 'RSVP mis à jour',
      for: 'pour',
      addedToCalendar: 'Ajouté au calendrier',
      icsFileDownloaded: 'Fichier ICS téléchargé.',
      shareLinkCopied: 'Lien de partage copié',
      linkFor: 'Lien pour',
      copiedToClipboard: 'copié dans le presse-papiers.',

      // Evaluation & Feedback
      evaluationFeedback: 'Évaluation et commentaires',
      monitorLearningProgress: 'Surveillez vos progrès d\'apprentissage et l\'efficacité de la formation.',
      postTrainingSurveys: 'Enquêtes post-formation',
      shareTrainingExperience: 'Partagez votre expérience de formation',
      takeSurvey: 'Répondre à l\'enquête',
      selfAssessment: 'Auto-évaluation',
      evaluateSkillsProgress: 'Évaluez vos compétences et vos progrès',
      startAssessment: 'Commencer l\'évaluation',
      surveyCompletion: 'Achèvement de l\'enquête',
      averageRating: 'Note moyenne',
      totalResponses: 'Total des réponses',
      overallScore: 'Score global',
      skillAssessment: 'Évaluation des compétences',
      recentFeedback: 'Commentaires récents',
      excellentCourseContent: 'Excellent contenu de cours et exemples pratiques.',
      veryHelpfulUnderstanding: 'Très utile pour comprendre les besoins des étudiants.',
      outstandingProgramRealWorld: 'Programme exceptionnel avec des applications du monde réel.',
      communicationSkills: 'Compétences en communication',
      technicalKnowledge: 'Connaissances techniques',
      leadershipSkills: 'Compétences en leadership',
      problemSolving: 'Résolution de problèmes',

      // Help & Support
      frequentlyAskedQuestions: 'Foire aux questions',
      findAnswersCommonQuestions: 'Trouvez des réponses aux questions courantes sur notre plateforme',
      generalQuestions: 'Questions générales',
      howToResetPassword: 'Comment réinitialiser mon mot de passe ?',
      resetPasswordAnswer: 'Pour réinitialiser votre mot de passe, cliquez sur le lien "Mot de passe oublié" sur la page de connexion et suivez les instructions envoyées à votre courriel.',
      howToUpdateProfile: 'Comment mettre à jour mes informations de profil ?',
      updateProfileAnswer: 'Vous pouvez mettre à jour vos informations de profil en cliquant sur votre photo de profil dans le coin supérieur droit et en sélectionnant "Modifier le profil".',
      systemRequirements: 'Quelles sont les exigences du système ?',
      systemRequirementsAnswer: 'Notre plateforme fonctionne mieux sur les dernières versions de Chrome, Firefox, Safari et Edge. Assurez-vous que JavaScript est activé.',
      howToContactSupport: 'Comment contacter le support ?',
      contactSupportAnswer: 'Vous pouvez contacter notre équipe de support via la page Contact Support ou en envoyant un courriel à support@uqtr.ca',
      mobileAppAvailable: 'Y a-t-il une application mobile disponible ?',
      mobileAppAnswer: 'Oui, notre application mobile est disponible pour les appareils iOS et Android. Vous pouvez la télécharger depuis l\'App Store ou Google Play Store.',
      wereHereToHelp: 'Nous sommes là pour vous aider ! Contactez notre équipe de support pour obtenir de l\'aide.',
      contactInformation: 'Informations de contact',
      emailUs: 'Envoyez-nous un courriel',
      callUs: 'Appelez-nous',
      workingHours: 'Heures de travail',
      mondayFridayHours: 'Lundi - Vendredi : 9h00 - 18h00',
      sendUsMessage: 'Envoyez-nous un message',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Jean Dupont',
      emailPlaceholder: 'jean@uqtr.ca',
      subjectPlaceholder: 'De quoi s\'agit-il ?',
      messagePlaceholder: 'Comment pouvons-nous vous aider ?',
      sendMessage: 'Envoyer le message',
      resetPasswordSimpleAnswer: 'Vous pouvez réinitialiser votre mot de passe en cliquant sur "Mot de passe oublié" sur la page de connexion.',
      updateProfileSimpleAnswer: 'Naviguez vers les paramètres de votre profil pour mettre à jour vos informations personnelles.',
      userGuidesDocumentation: 'Guides utilisateur et documentation',
      findHelpfulGuides: 'Trouvez des guides utiles, des tutoriels et de la documentation pour tirer le meilleur parti de notre plateforme.',
      gettingStartedGuide: 'Guide de démarrage',
      gettingStartedDescription: 'Apprenez à configurer votre compte et à naviguer sur la plateforme avec notre guide complet.',
      videoTutorials: 'Tutoriels vidéo',
      videoTutorialsDescription: 'Regardez des tutoriels vidéo étape par étape pour maîtriser toutes les fonctionnalités de notre plateforme.',
      apiDocumentation: 'Documentation API',
      apiDocumentationDescription: 'Documentation technique pour l\'intégration avec notre API et la création de solutions personnalisées.',
      keyboardShortcuts: 'Raccourcis clavier',
      keyboardShortcutsDescription: 'Augmentez votre productivité avec ces raccourcis clavier pratiques pour les actions courantes.',
      videoSeries: 'Série vidéo',
      web: 'Web',
      cheatSheet: 'Aide-mémoire',
      allGuides: 'Tous les guides',
      gettingStarted: 'Démarrage',
      features: 'Fonctionnalités',
      troubleshooting: 'Dépannage',
      viewGuide: 'Voir le guide',
      lastUpdated: 'Dernière mise à jour',
      cantFindWhatLookingFor: 'Vous ne trouvez pas ce que vous cherchez ?',
      supportTeamReadyToHelp: 'Notre équipe de support est toujours prête à vous aider avec toutes vos questions.',
      createSupportTicket: 'Créer un ticket de support',
      fillOutFormSubmitTicket: 'Remplissez le formulaire ci-dessous pour soumettre un ticket de support à notre équipe.',
      newSupportTicket: 'Nouveau ticket de support',
      brieflyDescribeIssue: 'Décrivez brièvement votre problème',
      selectPriority: 'Sélectionner la priorité',
      low: 'Faible',
      medium: 'Moyen',
      high: 'Élevé',
      urgent: 'Urgent',
      selectCategory: 'Sélectionner la catégorie',
      technicalIssue: 'Problème technique',
      billing: 'Facturation',
      account: 'Compte',
      featureRequest: 'Demande de fonctionnalité',
      other: 'Autre',
      provideDetailedInformation: 'Veuillez fournir des informations détaillées sur votre problème',
      attachments: 'Pièces jointes',
      addFiles: 'Ajouter des fichiers',
      filesAttached: 'fichier(s) joint(s)',
      submitTicket: 'Soumettre le ticket',

      // Task Management
      taskManagement: 'Gestion des tâches',
      organizeTrackTasksEfficiently: 'Organisez et suivez vos tâches efficacement',
      backToHome: 'Retour à l\'accueil',
      addNewTask: 'Ajouter une nouvelle tâche',
      createNewTask: 'Créer une nouvelle tâche',
      editTask: 'Modifier la tâche',
      taskTitle: 'Titre de la tâche',
      taskDescription: 'Description de la tâche',
      deadline: 'Échéance',
      deadlinePlaceholder: 'Échéance (ex: Aujourd\'hui, Demain, La semaine prochaine)',
      priority: 'Priorité',
      status: 'Statut',
      category: 'Catégorie',
      addTask: 'Ajouter la tâche',
      updateTask: 'Mettre à jour la tâche',
      cancel: 'Annuler',
      allTasks: 'Toutes les tâches',
      pleaseFillRequiredFields: 'Veuillez remplir tous les champs requis',
      taskAddedSuccessfully: 'Tâche ajoutée avec succès',
      taskUpdatedSuccessfully: 'Tâche mise à jour avec succès',
      taskDeletedSuccessfully: 'Tâche supprimée avec succès',
      taskMarkedAsPending: 'Tâche marquée comme en attente',
      taskCompleted: 'Tâche terminée',
      highPriority: 'Priorité élevée',
      mediumPriority: 'Priorité moyenne',
      lowPriority: 'Priorité faible',
      pending: 'En attente',
      inprogress: 'En cours',
      completed: 'Terminé',
      courseDevelopment: 'Développement de cours',
      assessment: 'Évaluation',
      contentUpdates: 'Mises à jour de contenu',
      administration: 'Administration',
      compliance: 'Conformité',
      trainingDelivery: 'Livraison de formation',
      today: 'Aujourd\'hui',
      tomorrow: 'Demain',
      nextWeek: 'La semaine prochaine',
      inTwoWeeks: 'Dans 2 semaines',
      nextMonth: 'Le mois prochain',
      thisFriday: 'Ce vendredi',
      reviewUQTRTrainingCatalogue: 'Examiner le contenu du catalogue de formation UQTR',
      reviewUQTRTrainingCatalogueDescription: 'Examiner et mettre à jour le contenu du catalogue de formation UQTR pour la précision et la conformité aux normes universitaires',
      gradeUQTRSelfRegistration: 'Noter les évaluations d\'auto-inscription UQTR',
      gradeUQTRSelfRegistrationDescription: 'Évaluer les récentes évaluations du système d\'auto-inscription UQTR et fournir des commentaires détaillés aux participants',
      prepareUQTRProgressTracking: 'Préparer l\'examen de suivi des progrès UQTR',
      prepareUQTRProgressTrackingDescription: 'Créer des questions d\'examen complètes pour l\'évaluation finale du module de suivi des progrès UQTR',
      updateUQTRComplianceMaterials: 'Mettre à jour les matériaux de formation de conformité UQTR',
      updateUQTRComplianceMaterialsDescription: 'Mettre à jour les matériaux de formation de conformité UQTR avec les dernières exigences réglementaires universitaires',
      scheduleUQTRInstructorSessions: 'Programmer les sessions d\'instructeurs UQTR',
      scheduleUQTRInstructorSessionsDescription: 'Établir l\'horaire de formation pour les instructeurs de faculté, d\'éducation et de développement étudiant UQTR',
      reviewUQTRStakeholderAnalysis: 'Examiner le module d\'analyse des parties prenantes UQTR',
      reviewUQTRStakeholderAnalysisDescription: 'Examen final du contenu du module d\'analyse des parties prenantes et d\'évaluation des besoins UQTR avant publication',

      // Today's Task Section
      todaysTask: 'Tâche d\'aujourd\'hui',
      newTask: 'Nouvelle tâche',
      viewAllTasks: 'Voir toutes les tâches',
      all: 'Toutes',
      open: 'Ouvertes',
      closed: 'Fermées',
      archived: 'Archivées',
      completeUQTRTrainingCatalogue: 'Compléter le catalogue de formation UQTR',
      completeUQTRTrainingCatalogueDescription: 'Fondements du système de catalogue de formation UQTR',
      reviewUQTRSelfRegistration: 'Examiner l\'auto-inscription UQTR',
      reviewUQTRSelfRegistrationDescription: 'Apprentissage professionnel dans l\'auto-inscription UQTR',
      submitUQTRProgressTracking: 'Soumettre le suivi des progrès UQTR',
      submitUQTRProgressTrackingDescription: 'Évaluation des besoins dans le suivi des progrès UQTR',

      // My Courses Section
      myCourses: 'Mes cours',
      viewAll: 'Voir tout',
      modules: 'modules',
      students: 'étudiants',
      uqtrUniversity: 'Université UQTR',
      buildingExcellenceFosteringGrowth: 'Construire l\'excellence, favoriser la croissance',
      progress: 'Progrès'
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
