import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  const translations = {
    en: {
      // Header
      search: 'Search...',
      calendar: 'Calendar',
      inbox: 'Inbox',
      notifications: 'Notifications',
      profile: 'Profile',
      logout: 'Log out',
      universityName: 'University of Quebec in Trois-Rivières (UQTR)',
      
      // Dashboard
      welcome: 'Welcome back',
      studentDashboard: 'Student Dashboard',
      haveProductiveDay: 'Have a productive day!',
      newTask: 'New Task',
      onlineCourse: 'Online Course',
      welcomeToUQTR: 'Welcome to UQTR',
      learningPlatform: 'Learning Platform',
      welcomeMessage: 'We\'re glad to see you here. Explore your courses, track your progress, and continue your professional development journey with us.',
      trainingCatalogue: 'Training Catalogue',
      selfRegistration: 'Self-Registration',
      progressTracking: 'Progress Tracking',
      multiFormatContent: 'Multi-Format Content',
      courseEnrollment: 'Course Enrollment',
      enrolled: 'Enrolled',
      completed: 'Completed',
      performance: 'Performance',
      myCourses: 'My Courses',
      viewAll: 'View All',
      todaysTask: 'Today\'s Task',
      newTask: 'New Task',
      all: 'All',
      open: 'Open',
      closed: 'Closed',
      archive: 'Archive',
      
      // Course details
      modules: 'modules',
      students: 'students',
      
      // Task details
      completeTrainingCatalogue: 'Complete Training Catalogue Setup',
      trainingCatalogueDescription: 'Configure course catalog for UQTR learners',
      reviewSelfRegistration: 'Review Self-Registration System',
      selfRegistrationDescription: 'Test and validate learner enrollment process',
      updateProgressReports: 'Update Progress Tracking Reports',
      progressReportsDescription: 'Generate monthly learning progress analytics',
      
      // Small stats
      integrationCapabilities: 'Integration Capabilities',
      ecommerceSupport: 'eCommerce Support',
      scormContent: 'SCORM Content',
      
      // Performance
      growthComparison: 'You have a 23% growth in comparison with last month.',
      
      // Calendar
      eventsFor: 'Events for',
      noEventsScheduled: 'No events scheduled',
      trainingCatalogueSetup: 'Training Catalogue Setup',
      selfRegistrationTraining: 'Self-Registration System Training',
      progressTrackingWorkshop: 'Progress Tracking Workshop',
      scormContentIntegration: 'SCORM Content Integration',
      ecommerceSupportTraining: 'eCommerce Support Training',
      integrationCapabilitiesWorkshop: 'Integration Capabilities Workshop',
      multiFormatContentTraining: 'Multi-Format Content Training',
      customizedCurriculum: 'Customized Curriculum & Scenario Design',
      assessmentWorkshop: 'Assessment & Evaluation Workshop',
      finalCertificationAssessment: 'Final Certification Assessment',
      module: 'module',
      workshop: 'workshop',
      
      // Months
      january: 'January',
      february: 'February',
      march: 'March',
      april: 'April',
      may: 'May',
      june: 'June',
      july: 'July',
      august: 'August',
      september: 'September',
      october: 'October',
      november: 'November',
      december: 'December',
      
      // Announcements
      announcements: 'Announcements',
      newTrainingCatalogueModule: 'New UQTR Training Catalogue Module Available',
      uqtrTrainingCoordinator: 'UQTR Training Coordinator',
      newTrainingCatalogueContent: 'Advanced UQTR Training Catalogue Module 2: Self-Registration & Progress Tracking is now available for enrollment.',
      scormIntegrationWorkshop: 'SCORM Content Integration Workshop',
      uqtrContentDepartment: 'UQTR Content Department',
      scormIntegrationContent: 'Join our upcoming workshop on SCORM 1.2/2004 content integration and multi-format support.',
      progressTrackingSurvey: 'Progress Tracking Analytics Survey',
      uqtrAnalyticsTeam: 'UQTR Analytics Team',
      progressTrackingSurveyContent: 'Please complete the progress tracking effectiveness survey to help us improve our analytics and reporting systems.',
      trainingManagement: 'Training Management',
      contentManagement: 'Content Management',
      analytics: 'Analytics',
      noAnnouncements: 'No announcements',
      checkBackLater: 'Check back later for updates',
      weekAgo: '1 week ago',
      hoursAgo: '2 hours ago',
      high: 'High',
      daysAgo: '5 days ago',
      
      // Zoom Classes
      zoomClassesManagement: 'Zoom Classes Management',
      upcomingClasses: 'Upcoming Classes',
      completedClasses: 'Completed Classes',
      noUpcomingClasses: 'No upcoming classes scheduled',
      scheduleFirstClass: 'Schedule your first class to get started',
      noCompletedClasses: 'No completed classes yet',
      completeFirstClass: 'Complete your first class to see it here',
      instructor: 'Instructor',
      joinViaZoom: 'Join via Zoom',
      viewRecording: 'View Recording',
      download: 'Download',
      completed: 'Completed',
      editClass: 'Edit Class',
      updateClass: 'Update Class',
      cancel: 'Cancel',
      recording: 'Recording',
      recordingPlayer: 'Recording Player',
      classHeldOn: 'Class held on',
      attendance: 'Attendance',
      students: 'students',
      downloadRecording: 'Download Recording',
      
      // Sidebar Navigation
      home: 'Home',
      courses: 'Courses',
      communityResources: 'Community Resources',
      catalog: 'Catalog',
      messages: 'Messages',
      games: 'Games',
      events: 'Events',
      evaluationFeedback: 'Evaluation & Feedback',
      helpSupport: 'Help & Support',
      adminPortal: 'Admin Portal',
      faqs: 'FAQs',
      contactSupport: 'Contact Support',
      userGuides: 'User Guides',
      supportTicket: 'Support Ticket',

      // Admin Portal
      overview: 'Overview',
      uploadCourses: 'Upload Courses',
      webinars: 'Webinars',
      schedule: 'Schedule',
      users: 'Users',
      reports: 'Reports',
      feedbackReports: 'Feedback Reports',
      overviewSummary: 'Overview Summary',
      dashboardAnalytics: 'Dashboard analytics and key metrics',
      totalUsers: 'Total Users',
      thisMonth: 'this month',
      platformActivity: 'Platform Activity',
      courseCompletions: 'Course Completions',
      activeSessions: 'Active Sessions',
      newRegistrations: 'New Registrations',
      supportTickets: 'Support Tickets',
      recentActivity: 'Recent Activity',
      newCourseUploaded: 'New course "Advanced Training" uploaded',
      webinarScheduled: 'Webinar "Safety Protocols" scheduled',
      monthlyReportGenerated: 'Monthly report generated',
      newUsersRegistered: '15 new users registered',
      hoursAgo: '2 hours ago',
      
      // Admin Portal - Additional Keys
      activeCourses: 'Active Courses',
      newThisWeek: 'new this week',
      scheduledWebinars: 'Scheduled Webinars',
      thisWeek: 'this week',
      pendingReports: 'Pending Reports',
      dueThisWeek: 'Due this week',
      performanceMetrics: 'Performance Metrics',
      systemUptime: 'System Uptime',
      last30Days: 'Last 30 days',
      avgLoadTime: 'Avg Load Time',
      pageResponse: 'Page response',
      userSatisfaction: 'User Satisfaction',
      recentSurveys: 'Recent surveys',
      quickActions: 'Quick Actions',
      uploadCourse: 'Upload Course',
      scheduleWebinar: 'Schedule Webinar',
      sendAnnouncement: 'Send Announcement',
      generateReport: 'Generate Report',
      courseManagement: 'Course Management',
      uploadManageOrganize: 'Upload, manage, and organize training courses',
      uploadNewCourse: 'Upload New Course',
      dropFilesToUpload: 'Drop files to upload',
      dropFilesHereOrClick: 'Drop files here or click to upload',
      supportForFormats: 'Support for SCORM, PDF, Video, and other formats',
      chooseFiles: 'Choose Files',
      createNewCourse: 'Create New Course',
      courseTitle: 'Course Title',
      enterCourseTitle: 'Enter course title',
      category: 'Category',
      lawEnforcementTraining: 'Law Enforcement Training',
      educatorTraining: 'Educator Training',
      youthAdvocacyTraining: 'Youth Advocacy Training',
      generalTraining: 'General Training',
      durationHours: 'Duration (hours)',
      enterDuration: 'Enter duration',
      difficultyLevel: 'Difficulty Level',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      description: 'Description',
      enterCourseDescription: 'Enter course description',
      learningObjectives: 'Learning Objectives',
      listLearningObjectives: 'List the key learning objectives for this course',
      createCourse: 'Create Course',
      saveAsDraft: 'Save as Draft',
      existingCourses: 'Existing Courses',
      all: 'All',
      published: 'Published',
      drafts: 'Drafts',
      lawEnforcementFundamentals: 'Law Enforcement Fundamentals',
      hours: 'hours',
      students: 'students',
      educatorTrainingProgram: 'Educator Training Program',
      youthAdvocacyWorkshop: 'Youth Advocacy Workshop',
      draft: 'Draft',
      coursePerformance: 'Course Performance',
      totalCourses: 'Total Courses',
      newThisMonth: 'new this month',
      totalCompletions: 'Total Completions',
      avgRating: 'Avg Rating',
      basedOnReviews: 'Based on 234 reviews',
      adminSection: 'Admin Section',
      selectSectionToGetStarted: 'Select a section from the sidebar to get started',
      
      // Webinar Management
      webinarManagement: 'Webinar Management',
      scheduleManageTrack: 'Schedule, manage, and track webinar sessions',
      scheduleWebinar: 'Schedule Webinar',
      webinarPerformance: 'Webinar Performance',
      scheduled: 'Scheduled',
      thisMonth: 'This month',
      totalAttendees: 'Total Attendees',
      attendanceRate: 'Attendance Rate',
      average: 'Average',
      avgRating: 'Avg Rating',
      basedOnReviews: 'Based on 89 reviews',
      upcomingWebinars: 'Upcoming Webinars',
      manageScheduledSessions: 'Manage your scheduled webinar sessions',
      allSessions: 'All Sessions',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      participants: 'participants',
      minutes: 'minutes',
      instructor: 'Instructor',
      startWebinar: 'Start Webinar',
      editWebinar: 'Edit Webinar',
      deleteWebinar: 'Delete Webinar',
      scheduleNewWebinar: 'Schedule New Webinar',
      fillInDetails: 'Fill in the details for your webinar session',
      webinarTitle: 'Webinar Title',
      enterWebinarTitle: 'Enter webinar title',
      selectInstructor: 'Select Instructor',
      lawEnforcement: 'Law Enforcement',
      education: 'Education',
      youthAdvocacy: 'Youth Advocacy',
      generalTraining: 'General Training',
      date: 'Date',
      time: 'Time',
      duration: 'Duration',
      maxParticipants: 'Max Participants',
      enterMaxParticipants: 'Enter max participants',
      minutes: 'minutes',
      hour: 'hour',
      hours: 'hours',
      updateWebinar: 'Update Webinar',
      scheduleWebinar: 'Schedule Webinar',
      cancel: 'Cancel',
      webinarCanOnlyBeStarted: 'Webinar can only be started within 30 minutes of scheduled time.',
      webinarIsNowLive: 'Webinar "{title}" is now live! Starting video conference...',
      
      // User Management
      userManagement: 'User Management',
      manageUsersRolesPermissions: 'Manage users, roles, and permissions',
      addUser: 'Add User',
      userStatistics: 'User Statistics',
      totalUsers: 'Total Users',
      activeUsers: 'Active Users',
      instructors: 'Instructors',
      inactiveUsers: 'Inactive Users',
      searchUsersByNameEmail: 'Search users by name, email, or department...',
      user: 'User',
      role: 'Role',
      department: 'Department',
      status: 'Status',
      lastLogin: 'Last Login',
      progress: 'Progress',
      actions: 'Actions',
      viewDetails: 'View Details',
      deactivate: 'Deactivate',
      activate: 'Activate',
      editUser: 'Edit User',
      deleteUser: 'Delete User',
      userDetails: 'User Details',
      joinDate: 'Join Date',
      coursesCompleted: 'Courses Completed',
      learningProgress: 'Learning Progress',
      totalHours: 'Total Hours',
      addNewUser: 'Add New User',
      updateUserInformation: 'Update user information',
      createNewUserAccount: 'Create a new user account',
      fullName: 'Full Name',
      enterFullName: 'Enter full name',
      emailAddress: 'Email Address',
      enterEmailAddress: 'Enter email address',
      student: 'Student',
      admin: 'Admin',
      active: 'Active',
      inactive: 'Inactive',
      enterDepartment: 'Enter department',
      updateUser: 'Update User',
      createUser: 'Create User',
      
      // Calendar Management
      calendarManagement: 'Calendar Management',
      scheduleManageTrainingSessions: 'Schedule and manage training sessions, meetings, and events',
      today: 'Today',
      addEvent: 'Add Event',
      october: 'October',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      sun: 'Sun',
      mon: 'Mon',
      tue: 'Tue',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      moreEvents: 'more events',
      upcomingEvents: 'Upcoming Events',
      eventStatistics: 'Event Statistics',
      training: 'Training',
      meeting: 'Meeting',
      workshop: 'Workshop',
      webinar: 'Webinar',
      assessment: 'Assessment',
      createNewEvent: 'Create New Event',
      updateEventDetails: 'Update the event details',
      scheduleNewEvent: 'Schedule a new event',
      eventTitle: 'Event Title',
      enterEventTitle: 'Enter event title',
      eventType: 'Event Type',
      durationMinutes: 'Duration (minutes)',
      location: 'Location',
      enterLocation: 'Enter location',
      expectedAttendees: 'Expected Attendees',
      instructorHost: 'Instructor/Host',
      enterInstructorName: 'Enter instructor name',
      updateEvent: 'Update Event',
      createEvent: 'Create Event',
      
      // Announcement Management
      announcementManagement: 'Announcement Management',
      createManageTrackAnnouncements: 'Create, manage, and track platform announcements',
      createAnnouncement: 'Create Announcement',
      analyticsOverview: 'Analytics Overview',
      realTimeAnnouncementMetrics: 'Real-time announcement metrics',
      totalAnnouncements: 'Total Announcements',
      published: 'Published',
      active: 'Active',
      totalViews: 'Total Views',
      avgViews: 'Avg Views',
      perPost: 'per post',
      announcements: 'Announcements',
      manageMonitorAnnouncements: 'Manage and monitor your announcements',
      all: 'All',
      drafts: 'Drafts',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      priority: 'Priority',
      targetAudience: 'Target Audience',
      views: 'views',
      by: 'By',
      unpublish: 'Unpublish',
      publish: 'Publish',
      editAnnouncement: 'Edit Announcement',
      deleteAnnouncement: 'Delete Announcement',
      priorityDistribution: 'Priority Distribution',
      ofTotal: 'of total',
      editAnnouncement: 'Edit Announcement',
      createNewAnnouncement: 'Create New Announcement',
      updateAnnouncementDetails: 'Update the announcement details',
      createPublishNewAnnouncement: 'Create and publish a new announcement',
      title: 'Title',
      enterDescriptiveTitle: 'Enter a descriptive title for your announcement',
      content: 'Content',
      writeAnnouncementContent: 'Write your announcement content here...',
      category: 'Category',
      trainingUpdate: 'Training Update',
      systemUpdate: 'System Update',
      report: 'Report',
      general: 'General',
      policyChange: 'Policy Change',
      event: 'Event',
      allUsers: 'All Users',
      administrators: 'Administrators',
      lawEnforcement: 'Law Enforcement',
      educators: 'Educators',
      youthAdvocates: 'Youth Advocates',
      updateAnnouncement: 'Update Announcement',
      publishAnnouncement: 'Publish Announcement',
      
      // Admin Reports
      administrativeReports: 'Administrative Reports',
      comprehensiveAnalyticsReporting: 'Comprehensive analytics and reporting dashboard',
      last30Days: 'Last 30 days',
      exportPDF: 'Export PDF',
      exportExcel: 'Export Excel',
      overview: 'Overview',
      enrollment: 'Enrollment',
      performance: 'Performance',
      completion: 'Completion',
      loadingData: 'Loading data...',
      dataUpdatedFor: 'Data updated for last {days} days!',
      generatingPDFReport: 'Generating PDF report...',
      pdfReportDownloadedSuccessfully: 'PDF report downloaded successfully!',
      failedToGeneratePDFReport: 'Failed to generate PDF report',
      generatingExcelReport: 'Generating Excel report...',
      excelReportDownloadedSuccessfully: 'Excel report downloaded successfully!',
      failedToGenerateExcelReport: 'Failed to generate Excel report',
      loadingOverviewData: 'Loading overview data...',
      overviewMetricsUpdated: 'Overview metrics updated with latest data',
      loadingEnrollmentData: 'Loading enrollment data...',
      enrollmentStatisticsRefreshed: 'Enrollment statistics refreshed successfully',
      loadingPerformanceData: 'Loading performance data...',
      performanceMetricsCalculated: 'Performance metrics calculated and updated',
      loadingCompletionData: 'Loading completion data...',
      completionRatesTrendsUpdated: 'Completion rates and trends updated',
      fromLastMonth: 'from last month',
      newThisMonth: 'new this month',
      improvement: 'improvement',
      enrollmentTrends: 'Enrollment Trends',
      monthlyEnrollmentCompletionRates: 'Monthly enrollment and completion rates',
      enrollments: 'Enrollments',
      completions: 'Completions',
      departmentDistribution: 'Department Distribution',
      userDistributionAcrossDepartments: 'User distribution across departments',
      enrollmentByCourse: 'Enrollment by Course',
      enrollmentSources: 'Enrollment Sources',
      directRegistration: 'Direct Registration',
      departmentReferral: 'Department Referral',
      emailCampaign: 'Email Campaign',
      geographicDistribution: 'Geographic Distribution',
      northeast: 'Northeast',
      southwest: 'Southwest',
      midwest: 'Midwest',
      westCoast: 'West Coast',
      enrollmentTrends: 'Enrollment Trends',
      thisMonth: 'This Month',
      lastMonth: 'Last Month',
      monthAvg: '3-Month Avg',
      coursePerformanceMetrics: 'Course Performance Metrics',
      course: 'Course',
      enrolled: 'Enrolled',
      completed: 'Completed',
      completionRate: 'Completion Rate',
      avgScore: 'Avg Score',
      avgTime: 'Avg Time',
      performanceTrends: 'Performance Trends',
      scoreDistribution: 'Score Distribution',
      below70: 'Below 70%',
      overallCompletionRate: 'Overall Completion Rate',
      avgTimeToComplete: 'Avg. Time to Complete',
      certificatesIssued: 'Certificates Issued',
      completionTimeline: 'Completion Timeline',
      completionByDepartment: 'Completion by Department',
      policeDepartments: 'Police Departments',
      educationalInstitutions: 'Educational Institutions',
      communityOrganizations: 'Community Organizations',
      completionFactors: 'Completion Factors',
      courseDifficulty: 'Course Difficulty',
      timeAvailability: 'Time Availability',
      supportQuality: 'Support Quality',
      highImpact: 'High Impact',
      mediumImpact: 'Medium Impact',
      
      // Admin Feedback Reports
      feedbackReports: 'Feedback Reports',
      analyzeLearnerFeedback: 'Analyze learner feedback and satisfaction metrics',
      export: 'Export',
      satisfaction: 'Satisfaction',
      categories: 'Categories',
      courses: 'Courses',
      avgSatisfaction: 'Avg Satisfaction',
      fromLastMonth: 'from last month',
      totalResponses: 'Total Responses',
      responseRate: 'Response Rate',
      positiveSentiment: 'Positive Sentiment',
      satisfactionTrend: 'Satisfaction Trend',
      sentimentDistribution: 'Sentiment Distribution',
      positive: 'Positive',
      negative: 'Negative',
      
      // Admin Events
      eventsManagement: 'Events Management',
      createManageShareEvents: 'Create, manage, and share upcoming events',
      exportCSV: 'Export CSV',
      createEvent: 'Create Event',
      searchByTitleLocation: 'Search by title or location...',
      allTypes: 'All types',
      reset: 'Reset',
      upcomingThisMonth: 'Upcoming this month',
      totalRsvps: 'Total RSVPs',
      avgCapacityUsed: 'Avg. capacity used',
      calendar: 'Calendar',
      viewUpcomingEventsMonthly: 'View upcoming events in a monthly view.',
      openCalendar: 'Open Calendar',
      manageRsvps: 'Manage RSVPs',
      trackAttendeeResponses: 'Track attendee responses and capacity.',
      viewRsvps: 'View RSVPs',
      quickAnnounce: 'Quick Announce',
      sendQuickEventAnnouncement: 'Send a quick event announcement.',
      send: 'Send',
      upcomingEvents: 'Upcoming events',
      results: 'result(s)',
      cybercrimeAwarenessWebinar: 'Cybercrime Awareness Webinar',
      online: 'Online',
      attending: 'attending',
      rsvps: 'RSVPs',
      share: 'Share',
      duplicate: 'Duplicate',
      unpublish: 'Unpublish',
      delete: 'Delete',
      communityOutreachBoston: 'Community Outreach - Boston',
      bostonMA: 'Boston, MA',
      shareLinkCopied: 'Share link copied',
      linkFor: 'Link for',
      copiedToClipboard: 'copied to clipboard.',
      csvExported: 'CSV exported',
      eventDataExported: 'Event data exported successfully.',
      youHave: 'You have',
      savedEvent: 'saved event',

      // Catalog & Groups
      trainingCatalog: 'Training Catalog',
      trainingCatalogDescription: 'Explore our comprehensive collection of UQTR training programs',
      searchPlaceholder: 'Search by name, description, or tags...',
      courses: 'Courses',
      exploreCatalog: 'Explore Catalog',
      noResultsFound: 'No Results Found',
      noResultsDescription: 'We couldn\'t find any catalogs matching your search. Try adjusting your search terms.',
      uqtrTrainingCatalogue: 'UQTR Training Catalogue',
      uqtrTrainingDescription: 'Comprehensive training management and course catalog system',
      uqtrSelfRegistration: 'UQTR Self-Registration',
      uqtrSelfRegistrationDescription: 'Automated learner enrollment and registration system',
      uqtrProgressTracking: 'UQTR Progress Tracking',
      uqtrProgressTrackingDescription: 'Advanced analytics and progress monitoring tools',
      weeks: '12 weeks',
      intermediate: 'Intermediate',
      beginner: 'Beginner',
      advanced: 'Advanced',
      systemAdministration: 'System Administration',
      userManagement: 'User Management',
      enrollment: 'Enrollment',
      reporting: 'Reporting',
      dataVisualization: 'Data Visualization',
      myCommunityResources: 'My Community Resources',
      communityResourcesDescription: 'Manage and participate in your enrolled community resources',
      discoverGroups: 'Discover Groups',
      searchMyGroups: 'Search my groups...',
      allTypes: 'All types',
      interestGroups: 'Interest groups',
      studyGroups: 'Study groups',
      businessGroups: 'Business groups',
      members: 'Members',
      openGroup: 'Open Group',
      enrolled: 'Enrolled',
      professionalTraining: 'Professional Training',
      communityDevelopment: 'Community Development',
      legalEducation: 'Legal Education',
      researchGroup: 'Research Group',
      studentOrganization: 'Student Organization',
      
      // Group Detail Page
      active: 'Active',
      trainingSessions: 'Training Sessions',
      certifications: 'Certifications',
      groupInformation: 'Group Information',
      category: 'Category',
      createdDate: 'Created Date',
      lastActivity: 'Last Activity',
      status: 'Status',
      totalMembers: 'Total Members',
      groupType: 'Group Type',
      recentActivity: 'Recent Activity',
      newTrainingSession: 'New training session: "Stakeholder Analysis & Needs Assessment"',
      newMembersJoined: '5 new officers joined the training program',
      certificationExamScheduled: 'Module 2 certification exam scheduled for next week',
      trainingMaterialsUpdated: 'DOJ compliance training materials updated',
      oneHourAgo: '1 hour ago',
      twoDaysAgo: '2 days ago',
      fourDaysAgo: '4 days ago',
      oneWeekAgo: '1 week ago',
      
      // UQTR Group Names
      uqtrLawEnforcementTraining: 'UQTR Law Enforcement Training Group',
      uqtrCommunityOutreach: 'UQTR Community Outreach Program',
      uqtrLegalTrainingSpecialists: 'UQTR Legal Training Specialists',
      
      // UQTR Group Descriptions
      uqtrLawEnforcementDescription: 'DOJ Law Enforcement Training Group focused on professional development, stakeholder analysis, and advanced law enforcement skills enhancement',
      uqtrCommunityOutreachDescription: 'Community development program focused on building partnerships, fostering community engagement, and promoting social development initiatives',
      uqtrLegalTrainingDescription: 'Legal education specialists group focused on advanced legal training, case studies, and professional development for legal professionals',
      
      // Group Categories
      lawEnforcementTraining: 'Law Enforcement Training',
      communityDevelopment: 'Community Development',
      legalEducation: 'Legal Education',
      
      // Group Status
      activeAcceptingTrainees: 'Active and accepting new trainees',
      activeAcceptingMembers: 'Active and accepting new members',
      activeAcceptingStudents: 'Active and accepting new students',
      
      // Dates
      january152024: 'January 15, 2024',
      february102024: 'February 10, 2024',
      march52024: 'March 5, 2024',
      
      // Time References
      oneHourAgo: '1 hour ago',
      twoHoursAgo: '2 hours ago',
      threeHoursAgo: '3 hours ago',
      
      // Member Counts
      fortyFiveOfficers: '45 officers',
      thirtyTwoMembers: '32 members',
      twentyEightStudents: '28 students',
      
      // Group Types
      professionalTrainingGroup: 'Professional Training Group',
      communityDevelopmentGroup: 'Community Development Group',
      legalEducationGroup: 'Legal Education Group',

      // Messages
      searchContacts: 'Search contacts...',
      newChat: 'New Chat',
      selectContact: 'Select Contact',
      searchUsers: 'Search users...',
      noUsersFound: 'No users found',
      voiceMessage: 'Voice message',
      pdfDocument: 'PDF Document',
      addImages: 'Add Images',
      addFiles: 'Add Files',
      typeMessage: 'Type a message...',
      emojis: 'Emojis',
      selectConversation: 'Select a conversation to start messaging',
      selectConversationDescription: 'Choose from your existing conversations or start a new one to connect with your learning community',

      // Contact Names
      sarahWilson: 'Sarah Wilson',
      michaelChen: 'Michael Chen',
      emilyBrown: 'Emily Brown',
      davidKim: 'David Kim',
      jessicaTaylor: 'Jessica Taylor',
      robertJohnson: 'Robert Johnson',

      // Contact Messages
      heyThere: 'Hey there!',
      letsCatchUpLater: 'Let\'s catch up later',
      didYouSeeNewCourse: 'Did you see the new course?',
      thanksForHelp: 'Thanks for your help!',
      areYouFreeTomorrow: 'Are you free tomorrow?',
      illGetBackToYou: 'I\'ll get back to you',

      // Sample Chat Messages
      hiHowAreYou: 'Hi! How are you?',
      imDoingGreat: 'I\'m doing great! Just finished the React module.',
      thatsAwesome: 'That\'s awesome! I\'m still working on it.',
      letMeKnowIfYouNeedHelp: 'Let me know if you need any help with it.',

      // Time References
      yesterday: 'Yesterday',
      twoDaysAgo: '2 days ago',

      // Events
      uqtrTrainingWorkshop: 'UQTR Training Workshop',
      uqtrCommunityOutreach: 'UQTR Community Outreach',
      uqtrPolicyRoundtable: 'UQTR Policy Roundtable',
      online: 'Online',
      troisRivieres: 'Trois-Rivières, QC',
      uqtrCampus: 'UQTR Campus',
      webinar: 'Webinar',
      outreach: 'Outreach',
      meeting: 'Meeting',
      discoverAndRsvp: 'Discover and RSVP to upcoming events.',
      myRsvps: 'My RSVPs',
      searchByTitleOrLocation: 'Search by title or location...',
      filterByType: 'Filter by type',
      reset: 'Reset',
      upcomingThisMonth: 'Upcoming this month',
      totalRsvps: 'Total RSVPs',
      avgCapacityUsed: 'Avg. capacity used',
      viewUpcomingEvents: 'View upcoming events in a monthly view.',
      openCalendar: 'Open Calendar',
      seeEventsResponded: 'See events you\'ve responded to.',
      viewRsvps: 'View RSVPs',
      subscribe: 'Subscribe',
      getEventReminders: 'Get event reminders and updates.',
      unsubscribe: 'Unsubscribe',
      upcomingEvents: 'Upcoming events',
      results: 'result(s)',
      attending: 'attending',
      updateRsvp: 'Update RSVP',
      rsvp: 'RSVP',
      rsvpTo: 'RSVP to',
      interested: 'Interested',
      notGoing: 'Not Going',
      cancel: 'Cancel',
      confirm: 'Confirm',
      saved: 'Saved',
      save: 'Save',
      addToCalendar: 'Add to Calendar',
      share: 'Share',
      youHave: 'You have',
      savedEvent: 'saved event',
      subscribed: 'Subscribed',
      unsubscribed: 'Unsubscribed',
      willReceiveReminders: 'You will receive reminders for upcoming events.',
      willNotReceiveReminders: 'You will no longer receive reminders.',
      rsvpUpdated: 'RSVP updated',
      for: 'for',
      addedToCalendar: 'Added to calendar',
      icsFileDownloaded: 'ICS file downloaded.',
      shareLinkCopied: 'Share link copied',
      linkFor: 'Link for',
      copiedToClipboard: 'copied to clipboard.',

      // Evaluation & Feedback
      evaluationFeedback: 'Evaluation & Feedback',
      monitorLearningProgress: 'Monitor your learning progress and training effectiveness.',
      postTrainingSurveys: 'Post-Training Surveys',
      shareTrainingExperience: 'Share your training experience',
      takeSurvey: 'Take Survey',
      selfAssessment: 'Self-Assessment',
      evaluateSkillsProgress: 'Evaluate your skills and progress',
      startAssessment: 'Start Assessment',
      surveyCompletion: 'Survey Completion',
      averageRating: 'Average Rating',
      totalResponses: 'Total Responses',
      overallScore: 'Overall Score',
      skillAssessment: 'Skill Assessment',
      recentFeedback: 'Recent Feedback',
      excellentCourseContent: 'Excellent course content and practical examples.',
      veryHelpfulUnderstanding: 'Very helpful for understanding student needs.',
      outstandingProgramRealWorld: 'Outstanding program with real-world applications.',
      communicationSkills: 'Communication Skills',
      technicalKnowledge: 'Technical Knowledge',
      leadershipSkills: 'Leadership Skills',
      problemSolving: 'Problem Solving',

      // Help & Support
      frequentlyAskedQuestions: 'Frequently Asked Questions',
      findAnswersCommonQuestions: 'Find answers to common questions about our platform',
      generalQuestions: 'General Questions',
      howToResetPassword: 'How do I reset my password?',
      resetPasswordAnswer: 'To reset your password, click on the "Forgot Password" link on the login page and follow the instructions sent to your email.',
      howToUpdateProfile: 'How do I update my profile information?',
      updateProfileAnswer: 'You can update your profile information by clicking on your profile picture in the top right corner and selecting "Edit Profile".',
      systemRequirements: 'What are the system requirements?',
      systemRequirementsAnswer: 'Our platform works best on the latest versions of Chrome, Firefox, Safari, and Edge. Make sure you have JavaScript enabled.',
      howToContactSupport: 'How do I contact support?',
      contactSupportAnswer: 'You can contact our support team through the Contact Support page or by emailing support@uqtr.ca',
      mobileAppAvailable: 'Is there a mobile app available?',
      mobileAppAnswer: 'Yes, our mobile app is available for both iOS and Android devices. You can download it from the App Store or Google Play Store.',
      wereHereToHelp: 'We\'re here to help! Reach out to our support team for assistance.',
      contactInformation: 'Contact Information',
      emailUs: 'Email Us',
      callUs: 'Call Us',
      workingHours: 'Working Hours',
      mondayFridayHours: 'Monday - Friday: 9:00 AM - 6:00 PM',
      sendUsMessage: 'Send us a Message',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      emailPlaceholder: 'john@uqtr.ca',
      subjectPlaceholder: 'What\'s this about?',
      messagePlaceholder: 'How can we help you?',
      sendMessage: 'Send Message',
      resetPasswordSimpleAnswer: 'You can reset your password by clicking on "Forgot Password" on the login page.',
      updateProfileSimpleAnswer: 'Navigate to your profile settings to update your personal information.',
      userGuidesDocumentation: 'User Guides & Documentation',
      findHelpfulGuides: 'Find helpful guides, tutorials, and documentation to get the most out of our platform.',
      gettingStartedGuide: 'Getting Started Guide',
      gettingStartedDescription: 'Learn how to set up your account and navigate the platform with our comprehensive guide.',
      videoTutorials: 'Video Tutorials',
      videoTutorialsDescription: 'Watch step-by-step video tutorials to master all the features of our platform.',
      apiDocumentation: 'API Documentation',
      apiDocumentationDescription: 'Technical documentation for integrating with our API and building custom solutions.',
      keyboardShortcuts: 'Keyboard Shortcuts',
      keyboardShortcutsDescription: 'Boost your productivity with these handy keyboard shortcuts for common actions.',
      videoSeries: 'Video Series',
      web: 'Web',
      cheatSheet: 'Cheat Sheet',
      allGuides: 'All Guides',
      gettingStarted: 'Getting Started',
      features: 'Features',
      troubleshooting: 'Troubleshooting',
      viewGuide: 'View Guide',
      lastUpdated: 'Last updated',
      cantFindWhatLookingFor: 'Can\'t find what you\'re looking for?',
      supportTeamReadyToHelp: 'Our support team is always ready to help with any questions you might have.',
      createSupportTicket: 'Create Support Ticket',
      fillOutFormSubmitTicket: 'Fill out the form below to submit a support ticket to our team.',
      newSupportTicket: 'New Support Ticket',
      brieflyDescribeIssue: 'Briefly describe your issue',
      selectPriority: 'Select priority',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      selectCategory: 'Select category',
      technicalIssue: 'Technical Issue',
      billing: 'Billing',
      account: 'Account',
      featureRequest: 'Feature Request',
      other: 'Other',
      provideDetailedInformation: 'Please provide detailed information about your issue',
      attachments: 'Attachments',
      addFiles: 'Add Files',
      filesAttached: 'file(s) attached',
      submitTicket: 'Submit Ticket',

      // Task Management
      taskManagement: 'Task Management',
      organizeTrackTasksEfficiently: 'Organize and track your tasks efficiently',
      backToHome: 'Back to Home',
      addNewTask: 'Add New Task',
      createNewTask: 'Create New Task',
      editTask: 'Edit Task',
      taskTitle: 'Task title',
      taskDescription: 'Task description',
      deadline: 'Deadline',
      deadlinePlaceholder: 'Deadline (e.g., Today, Tomorrow, Next week)',
      priority: 'Priority',
      status: 'Status',
      category: 'Category',
      addTask: 'Add Task',
      updateTask: 'Update Task',
      cancel: 'Cancel',
      allTasks: 'All Tasks',
      pleaseFillRequiredFields: 'Please fill in all required fields',
      taskAddedSuccessfully: 'Task added successfully',
      taskUpdatedSuccessfully: 'Task updated successfully',
      taskDeletedSuccessfully: 'Task deleted successfully',
      taskMarkedAsPending: 'Task marked as pending',
      taskCompleted: 'Task completed',
      highPriority: 'High Priority',
      mediumPriority: 'Medium Priority',
      lowPriority: 'Low Priority',
      pending: 'Pending',
      inprogress: 'In Progress',
      completed: 'Completed',
      courseDevelopment: 'Course Development',
      assessment: 'Assessment',
      contentUpdates: 'Content Updates',
      administration: 'Administration',
      compliance: 'Compliance',
      trainingDelivery: 'Training Delivery',
      today: 'Today',
      tomorrow: 'Tomorrow',
      nextWeek: 'Next week',
      inTwoWeeks: 'In 2 weeks',
      nextMonth: 'Next month',
      thisFriday: 'This Friday',
      reviewUQTRTrainingCatalogue: 'Review UQTR Training Catalogue Content',
      reviewUQTRTrainingCatalogueDescription: 'Review and update UQTR Training Catalogue content for accuracy and compliance with university standards',
      gradeUQTRSelfRegistration: 'Grade UQTR Self-Registration Assessments',
      gradeUQTRSelfRegistrationDescription: 'Evaluate recent UQTR Self-Registration system assessments and provide detailed feedback to participants',
      prepareUQTRProgressTracking: 'Prepare UQTR Progress Tracking Exam',
      prepareUQTRProgressTrackingDescription: 'Create comprehensive exam questions for UQTR Progress Tracking Module final assessment',
      updateUQTRComplianceMaterials: 'Update UQTR Compliance Training Materials',
      updateUQTRComplianceMaterialsDescription: 'Update UQTR compliance training materials with latest university regulatory requirements',
      scheduleUQTRInstructorSessions: 'Schedule UQTR Instructor Sessions',
      scheduleUQTRInstructorSessionsDescription: 'Set up training schedule for UQTR faculty, education, and student development instructors',
      reviewUQTRStakeholderAnalysis: 'Review UQTR Stakeholder Analysis Module',
      reviewUQTRStakeholderAnalysisDescription: 'Final review of UQTR Stakeholder Analysis & Needs Assessment module content before publication',

      // Today's Task Section
      todaysTask: 'Today\'s Task',
      newTask: 'New Task',
      viewAllTasks: 'View All Tasks',
      all: 'All',
      open: 'Open',
      closed: 'Closed',
      archived: 'Archived',
      completeUQTRTrainingCatalogue: 'Complete UQTR Training Catalogue',
      completeUQTRTrainingCatalogueDescription: 'Foundations of UQTR Training Catalogue System',
      reviewUQTRSelfRegistration: 'Review UQTR Self-Registration',
      reviewUQTRSelfRegistrationDescription: 'Professional Learning in UQTR Self-Registration',
      submitUQTRProgressTracking: 'Submit UQTR Progress Tracking',
      submitUQTRProgressTrackingDescription: 'Needs Assessment in UQTR Progress Tracking',

      // My Courses Section
      myCourses: 'My Courses',
      viewAll: 'View All',
      modules: 'modules',
      students: 'students',
      uqtrUniversity: 'UQTR University',
      buildingExcellenceFosteringGrowth: 'Building Excellence, Fostering Growth',
      progress: 'Progress'
    },
    fr: {
      // Header
      search: 'Rechercher...',
      calendar: 'Calendrier',
      inbox: 'Boîte de réception',
      notifications: 'Notifications',
      profile: 'Profil',
      logout: 'Se déconnecter',
      universityName: 'University of Quebec in Trois-Rivières (UQTR)',
      
      // Dashboard
      welcome: 'Bon retour',
      studentDashboard: 'Tableau de bord étudiant',
      haveProductiveDay: 'Passez une journée productive !',
      newTask: 'Nouvelle tâche',
      onlineCourse: 'Cours en ligne',
      welcomeToUQTR: 'Bienvenue à l\'UQTR',
      learningPlatform: 'Plateforme d\'apprentissage',
      welcomeMessage: 'Nous sommes heureux de vous voir ici. Explorez vos cours, suivez vos progrès et continuez votre parcours de développement professionnel avec nous.',
      trainingCatalogue: 'Catalogue de formation',
      selfRegistration: 'Auto-inscription',
      progressTracking: 'Suivi des progrès',
      multiFormatContent: 'Contenu multi-format',
      courseEnrollment: 'Inscription aux cours',
      enrolled: 'Inscrit',
      completed: 'Terminé',
      performance: 'Performance',
      myCourses: 'Mes cours',
      viewAll: 'Voir tout',
      todaysTask: 'Tâche d\'aujourd\'hui',
      newTask: 'Nouvelle tâche',
      all: 'Tout',
      open: 'Ouvert',
      closed: 'Fermé',
      archive: 'Archives',
      
      // Course details
      modules: 'modules',
      students: 'étudiants',
      
      // Task details
      completeTrainingCatalogue: 'Compléter la configuration du catalogue de formation',
      trainingCatalogueDescription: 'Configurer le catalogue de cours pour les apprenants UQTR',
      reviewSelfRegistration: 'Examiner le système d\'auto-inscription',
      selfRegistrationDescription: 'Tester et valider le processus d\'inscription des apprenants',
      updateProgressReports: 'Mettre à jour les rapports de suivi des progrès',
      progressReportsDescription: 'Générer les analyses mensuelles des progrès d\'apprentissage',
      
      // Small stats
      integrationCapabilities: 'Capacités d\'intégration',
      ecommerceSupport: 'Support eCommerce',
      scormContent: 'Contenu SCORM',
      
      // Performance
      growthComparison: 'Vous avez une croissance de 23% par rapport au mois dernier.',
      
      // Calendar
      eventsFor: 'Événements pour le',
      noEventsScheduled: 'Aucun événement programmé',
      trainingCatalogueSetup: 'Configuration du catalogue de formation',
      selfRegistrationTraining: 'Formation au système d\'auto-inscription',
      progressTrackingWorkshop: 'Atelier de suivi des progrès',
      scormContentIntegration: 'Intégration de contenu SCORM',
      ecommerceSupportTraining: 'Formation au support eCommerce',
      integrationCapabilitiesWorkshop: 'Atelier sur les capacités d\'intégration',
      multiFormatContentTraining: 'Formation au contenu multi-format',
      customizedCurriculum: 'Conception de programme et de scénario personnalisé',
      assessmentWorkshop: 'Atelier d\'évaluation et d\'évaluation',
      finalCertificationAssessment: 'Évaluation de certification finale',
      module: 'module',
      workshop: 'atelier',
      
      // Months
      january: 'Janvier',
      february: 'Février',
      march: 'Mars',
      april: 'Avril',
      may: 'Mai',
      june: 'Juin',
      july: 'Juillet',
      august: 'Août',
      september: 'Septembre',
      october: 'Octobre',
      november: 'Novembre',
      december: 'Décembre',
      
      // Announcements
      announcements: 'Annonces',
      newTrainingCatalogueModule: 'Nouveau module de catalogue de formation UQTR disponible',
      uqtrTrainingCoordinator: 'Coordinateur de formation UQTR',
      newTrainingCatalogueContent: 'Module avancé de catalogue de formation UQTR 2: Auto-inscription et suivi des progrès est maintenant disponible pour inscription.',
      scormIntegrationWorkshop: 'Atelier d\'intégration de contenu SCORM',
      uqtrContentDepartment: 'Département de contenu UQTR',
      scormIntegrationContent: 'Rejoignez notre prochain atelier sur l\'intégration de contenu SCORM 1.2/2004 et le support multi-format.',
      progressTrackingSurvey: 'Enquête sur les analyses de suivi des progrès',
      uqtrAnalyticsTeam: 'Équipe d\'analyses UQTR',
      progressTrackingSurveyContent: 'Veuillez compléter l\'enquête sur l\'efficacité du suivi des progrès pour nous aider à améliorer nos systèmes d\'analyses et de rapports.',
      trainingManagement: 'Gestion de formation',
      contentManagement: 'Gestion de contenu',
      analytics: 'Analyses',
      noAnnouncements: 'Aucune annonce',
      checkBackLater: 'Revenez plus tard pour les mises à jour',
      weekAgo: 'il y a 1 semaine',
      hoursAgo: 'il y a 2 heures',
      high: 'Élevé',
      daysAgo: 'il y a 5 jours',
      
      // Zoom Classes
      zoomClassesManagement: 'Gestion des classes Zoom',
      upcomingClasses: 'Classes à venir',
      completedClasses: 'Classes terminées',
      noUpcomingClasses: 'Aucune classe à venir programmée',
      scheduleFirstClass: 'Programmez votre première classe pour commencer',
      noCompletedClasses: 'Aucune classe terminée pour le moment',
      completeFirstClass: 'Terminez votre première classe pour la voir ici',
      instructor: 'Instructeur',
      joinViaZoom: 'Rejoindre via Zoom',
      viewRecording: 'Voir l\'enregistrement',
      download: 'Télécharger',
      completed: 'Terminé',
      editClass: 'Modifier la classe',
      updateClass: 'Mettre à jour la classe',
      cancel: 'Annuler',
      recording: 'Enregistrement',
      recordingPlayer: 'Lecteur d\'enregistrement',
      classHeldOn: 'Classe tenue le',
      attendance: 'Présence',
      students: 'étudiants',
      downloadRecording: 'Télécharger l\'enregistrement',
      
      // Sidebar Navigation
      home: 'Accueil',
      courses: 'Cours',
      communityResources: 'Ressources communautaires',
      catalog: 'Catalogue',
      messages: 'Messages',
      games: 'Jeux',
      events: 'Événements',
      evaluationFeedback: 'Évaluation et commentaires',
      helpSupport: 'Aide et support',
      adminPortal: 'Portail administrateur',
      faqs: 'FAQ',
      contactSupport: 'Contacter le support',
      userGuides: 'Guides utilisateur',
      supportTicket: 'Ticket de support',

      // Admin Portal
      overview: 'Aperçu',
      uploadCourses: 'Télécharger des cours',
      webinars: 'Webinaires',
      schedule: 'Planification',
      users: 'Utilisateurs',
      reports: 'Rapports',
      feedbackReports: 'Rapports de commentaires',
      overviewSummary: 'Résumé de l\'aperçu',
      dashboardAnalytics: 'Analyses du tableau de bord et métriques clés',
      totalUsers: 'Total des utilisateurs',
      thisMonth: 'ce mois-ci',
      platformActivity: 'Activité de la plateforme',
      courseCompletions: 'Achèvements de cours',
      activeSessions: 'Sessions actives',
      newRegistrations: 'Nouvelles inscriptions',
      supportTickets: 'Tickets de support',
      recentActivity: 'Activité récente',
      newCourseUploaded: 'Nouveau cours "Formation avancée" téléchargé',
      webinarScheduled: 'Webinaire "Protocoles de sécurité" programmé',
      monthlyReportGenerated: 'Rapport mensuel généré',
      newUsersRegistered: '15 nouveaux utilisateurs inscrits',
      hoursAgo: 'il y a 2 heures',
      
      // Admin Portal - Additional Keys
      activeCourses: 'Cours actifs',
      newThisWeek: 'nouveaux cette semaine',
      scheduledWebinars: 'Webinaires programmés',
      thisWeek: 'cette semaine',
      pendingReports: 'Rapports en attente',
      dueThisWeek: 'Échéance cette semaine',
      performanceMetrics: 'Métriques de performance',
      systemUptime: 'Temps de fonctionnement du système',
      last30Days: '30 derniers jours',
      avgLoadTime: 'Temps de chargement moyen',
      pageResponse: 'Réponse de page',
      userSatisfaction: 'Satisfaction utilisateur',
      recentSurveys: 'Enquêtes récentes',
      quickActions: 'Actions rapides',
      uploadCourse: 'Télécharger un cours',
      scheduleWebinar: 'Programmer un webinaire',
      sendAnnouncement: 'Envoyer une annonce',
      generateReport: 'Générer un rapport',
      courseManagement: 'Gestion des cours',
      uploadManageOrganize: 'Télécharger, gérer et organiser les cours de formation',
      uploadNewCourse: 'Télécharger un nouveau cours',
      dropFilesToUpload: 'Déposez les fichiers à télécharger',
      dropFilesHereOrClick: 'Déposez les fichiers ici ou cliquez pour télécharger',
      supportForFormats: 'Support pour SCORM, PDF, Vidéo et autres formats',
      chooseFiles: 'Choisir les fichiers',
      createNewCourse: 'Créer un nouveau cours',
      courseTitle: 'Titre du cours',
      enterCourseTitle: 'Entrez le titre du cours',
      category: 'Catégorie',
      lawEnforcementTraining: 'Formation en application de la loi',
      educatorTraining: 'Formation d\'éducateur',
      youthAdvocacyTraining: 'Formation en défense des jeunes',
      generalTraining: 'Formation générale',
      durationHours: 'Durée (heures)',
      enterDuration: 'Entrez la durée',
      difficultyLevel: 'Niveau de difficulté',
      beginner: 'Débutant',
      intermediate: 'Intermédiaire',
      advanced: 'Avancé',
      description: 'Description',
      enterCourseDescription: 'Entrez la description du cours',
      learningObjectives: 'Objectifs d\'apprentissage',
      listLearningObjectives: 'Listez les objectifs d\'apprentissage clés pour ce cours',
      createCourse: 'Créer le cours',
      saveAsDraft: 'Enregistrer comme brouillon',
      existingCourses: 'Cours existants',
      all: 'Tout',
      published: 'Publié',
      drafts: 'Brouillons',
      lawEnforcementFundamentals: 'Fondamentaux de l\'application de la loi',
      hours: 'heures',
      students: 'étudiants',
      educatorTrainingProgram: 'Programme de formation d\'éducateur',
      youthAdvocacyWorkshop: 'Atelier de défense des jeunes',
      draft: 'Brouillon',
      coursePerformance: 'Performance du cours',
      totalCourses: 'Total des cours',
      newThisMonth: 'nouveaux ce mois-ci',
      totalCompletions: 'Total des achèvements',
      avgRating: 'Note moyenne',
      basedOnReviews: 'Basé sur 234 avis',
      adminSection: 'Section administrateur',
      selectSectionToGetStarted: 'Sélectionnez une section dans la barre latérale pour commencer',
      
      // Webinar Management
      webinarManagement: 'Gestion des webinaires',
      scheduleManageTrack: 'Programmer, gérer et suivre les sessions de webinaires',
      scheduleWebinar: 'Programmer un webinaire',
      webinarPerformance: 'Performance des webinaires',
      scheduled: 'Programmé',
      thisMonth: 'Ce mois-ci',
      totalAttendees: 'Total des participants',
      attendanceRate: 'Taux de participation',
      average: 'Moyenne',
      avgRating: 'Note moyenne',
      basedOnReviews: 'Basé sur 89 avis',
      upcomingWebinars: 'Webinaires à venir',
      manageScheduledSessions: 'Gérez vos sessions de webinaires programmées',
      allSessions: 'Toutes les sessions',
      thisWeek: 'Cette semaine',
      thisMonth: 'Ce mois-ci',
      participants: 'participants',
      minutes: 'minutes',
      instructor: 'Instructeur',
      startWebinar: 'Démarrer le webinaire',
      editWebinar: 'Modifier le webinaire',
      deleteWebinar: 'Supprimer le webinaire',
      scheduleNewWebinar: 'Programmer un nouveau webinaire',
      fillInDetails: 'Remplissez les détails de votre session de webinaire',
      webinarTitle: 'Titre du webinaire',
      enterWebinarTitle: 'Entrez le titre du webinaire',
      selectInstructor: 'Sélectionner un instructeur',
      lawEnforcement: 'Application de la loi',
      education: 'Éducation',
      youthAdvocacy: 'Défense des jeunes',
      generalTraining: 'Formation générale',
      date: 'Date',
      time: 'Heure',
      duration: 'Durée',
      maxParticipants: 'Participants max',
      enterMaxParticipants: 'Entrez le nombre max de participants',
      minutes: 'minutes',
      hour: 'heure',
      hours: 'heures',
      updateWebinar: 'Mettre à jour le webinaire',
      scheduleWebinar: 'Programmer le webinaire',
      cancel: 'Annuler',
      webinarCanOnlyBeStarted: 'Le webinaire ne peut être démarré que dans les 30 minutes suivant l\'heure programmée.',
      webinarIsNowLive: 'Le webinaire "{title}" est maintenant en direct ! Démarrage de la conférence vidéo...',
      
      // User Management
      userManagement: 'Gestion des utilisateurs',
      manageUsersRolesPermissions: 'Gérer les utilisateurs, rôles et permissions',
      addUser: 'Ajouter un utilisateur',
      userStatistics: 'Statistiques des utilisateurs',
      totalUsers: 'Total des utilisateurs',
      activeUsers: 'Utilisateurs actifs',
      instructors: 'Instructeurs',
      inactiveUsers: 'Utilisateurs inactifs',
      searchUsersByNameEmail: 'Rechercher des utilisateurs par nom, email ou département...',
      user: 'Utilisateur',
      role: 'Rôle',
      department: 'Département',
      status: 'Statut',
      lastLogin: 'Dernière connexion',
      progress: 'Progrès',
      actions: 'Actions',
      viewDetails: 'Voir les détails',
      deactivate: 'Désactiver',
      activate: 'Activer',
      editUser: 'Modifier l\'utilisateur',
      deleteUser: 'Supprimer l\'utilisateur',
      userDetails: 'Détails de l\'utilisateur',
      joinDate: 'Date d\'inscription',
      coursesCompleted: 'Cours terminés',
      learningProgress: 'Progrès d\'apprentissage',
      totalHours: 'Total des heures',
      addNewUser: 'Ajouter un nouvel utilisateur',
      updateUserInformation: 'Mettre à jour les informations de l\'utilisateur',
      createNewUserAccount: 'Créer un nouveau compte utilisateur',
      fullName: 'Nom complet',
      enterFullName: 'Entrez le nom complet',
      emailAddress: 'Adresse email',
      enterEmailAddress: 'Entrez l\'adresse email',
      student: 'Étudiant',
      admin: 'Administrateur',
      active: 'Actif',
      inactive: 'Inactif',
      enterDepartment: 'Entrez le département',
      updateUser: 'Mettre à jour l\'utilisateur',
      createUser: 'Créer l\'utilisateur',
      
      // Calendar Management
      calendarManagement: 'Gestion du calendrier',
      scheduleManageTrainingSessions: 'Programmer et gérer les sessions de formation, réunions et événements',
      today: 'Aujourd\'hui',
      addEvent: 'Ajouter un événement',
      october: 'Octobre',
      day: 'Jour',
      week: 'Semaine',
      month: 'Mois',
      sun: 'Dim',
      mon: 'Lun',
      tue: 'Mar',
      wed: 'Mer',
      thu: 'Jeu',
      fri: 'Ven',
      sat: 'Sam',
      moreEvents: 'plus d\'événements',
      upcomingEvents: 'Événements à venir',
      eventStatistics: 'Statistiques des événements',
      training: 'Formation',
      meeting: 'Réunion',
      workshop: 'Atelier',
      webinar: 'Webinaire',
      assessment: 'Évaluation',
      createNewEvent: 'Créer un nouvel événement',
      updateEventDetails: 'Mettre à jour les détails de l\'événement',
      scheduleNewEvent: 'Programmer un nouvel événement',
      eventTitle: 'Titre de l\'événement',
      enterEventTitle: 'Entrez le titre de l\'événement',
      eventType: 'Type d\'événement',
      durationMinutes: 'Durée (minutes)',
      location: 'Lieu',
      enterLocation: 'Entrez le lieu',
      expectedAttendees: 'Participants attendus',
      instructorHost: 'Instructeur/Animateur',
      enterInstructorName: 'Entrez le nom de l\'instructeur',
      updateEvent: 'Mettre à jour l\'événement',
      createEvent: 'Créer l\'événement',
      
      // Announcement Management
      announcementManagement: 'Gestion des annonces',
      createManageTrackAnnouncements: 'Créer, gérer et suivre les annonces de la plateforme',
      createAnnouncement: 'Créer une annonce',
      analyticsOverview: 'Aperçu des analyses',
      realTimeAnnouncementMetrics: 'Métriques d\'annonces en temps réel',
      totalAnnouncements: 'Total des annonces',
      published: 'Publié',
      active: 'Actif',
      totalViews: 'Total des vues',
      avgViews: 'Vues moyennes',
      perPost: 'par publication',
      announcements: 'Annonces',
      manageMonitorAnnouncements: 'Gérer et surveiller vos annonces',
      all: 'Tout',
      drafts: 'Brouillons',
      high: 'Élevé',
      medium: 'Moyen',
      low: 'Faible',
      priority: 'Priorité',
      targetAudience: 'Public cible',
      views: 'vues',
      by: 'Par',
      unpublish: 'Dépublier',
      publish: 'Publier',
      editAnnouncement: 'Modifier l\'annonce',
      deleteAnnouncement: 'Supprimer l\'annonce',
      priorityDistribution: 'Distribution des priorités',
      ofTotal: 'du total',
      editAnnouncement: 'Modifier l\'annonce',
      createNewAnnouncement: 'Créer une nouvelle annonce',
      updateAnnouncementDetails: 'Mettre à jour les détails de l\'annonce',
      createPublishNewAnnouncement: 'Créer et publier une nouvelle annonce',
      title: 'Titre',
      enterDescriptiveTitle: 'Entrez un titre descriptif pour votre annonce',
      content: 'Contenu',
      writeAnnouncementContent: 'Écrivez le contenu de votre annonce ici...',
      category: 'Catégorie',
      trainingUpdate: 'Mise à jour de formation',
      systemUpdate: 'Mise à jour système',
      report: 'Rapport',
      general: 'Général',
      policyChange: 'Changement de politique',
      event: 'Événement',
      allUsers: 'Tous les utilisateurs',
      administrators: 'Administrateurs',
      lawEnforcement: 'Application de la loi',
      educators: 'Éducateurs',
      youthAdvocates: 'Défenseurs des jeunes',
      updateAnnouncement: 'Mettre à jour l\'annonce',
      publishAnnouncement: 'Publier l\'annonce',
      
      // Admin Reports
      administrativeReports: 'Rapports administratifs',
      comprehensiveAnalyticsReporting: 'Tableau de bord d\'analyses et de rapports complets',
      last30Days: '30 derniers jours',
      exportPDF: 'Exporter PDF',
      exportExcel: 'Exporter Excel',
      overview: 'Aperçu',
      enrollment: 'Inscription',
      performance: 'Performance',
      completion: 'Achèvement',
      loadingData: 'Chargement des données...',
      dataUpdatedFor: 'Données mises à jour pour les {days} derniers jours !',
      generatingPDFReport: 'Génération du rapport PDF...',
      pdfReportDownloadedSuccessfully: 'Rapport PDF téléchargé avec succès !',
      failedToGeneratePDFReport: 'Échec de la génération du rapport PDF',
      generatingExcelReport: 'Génération du rapport Excel...',
      excelReportDownloadedSuccessfully: 'Rapport Excel téléchargé avec succès !',
      failedToGenerateExcelReport: 'Échec de la génération du rapport Excel',
      loadingOverviewData: 'Chargement des données d\'aperçu...',
      overviewMetricsUpdated: 'Métriques d\'aperçu mises à jour avec les dernières données',
      loadingEnrollmentData: 'Chargement des données d\'inscription...',
      enrollmentStatisticsRefreshed: 'Statistiques d\'inscription actualisées avec succès',
      loadingPerformanceData: 'Chargement des données de performance...',
      performanceMetricsCalculated: 'Métriques de performance calculées et mises à jour',
      loadingCompletionData: 'Chargement des données d\'achèvement...',
      completionRatesTrendsUpdated: 'Taux d\'achèvement et tendances mis à jour',
      fromLastMonth: 'du mois dernier',
      newThisMonth: 'nouveaux ce mois-ci',
      improvement: 'amélioration',
      enrollmentTrends: 'Tendances d\'inscription',
      monthlyEnrollmentCompletionRates: 'Taux d\'inscription et d\'achèvement mensuels',
      enrollments: 'Inscriptions',
      completions: 'Achèvements',
      departmentDistribution: 'Distribution par département',
      userDistributionAcrossDepartments: 'Distribution des utilisateurs par départements',
      enrollmentByCourse: 'Inscription par cours',
      enrollmentSources: 'Sources d\'inscription',
      directRegistration: 'Inscription directe',
      departmentReferral: 'Référence départementale',
      emailCampaign: 'Campagne email',
      geographicDistribution: 'Distribution géographique',
      northeast: 'Nord-Est',
      southwest: 'Sud-Ouest',
      midwest: 'Midwest',
      westCoast: 'Côte Ouest',
      enrollmentTrends: 'Tendances d\'inscription',
      thisMonth: 'Ce mois-ci',
      lastMonth: 'Le mois dernier',
      monthAvg: 'Moyenne 3 mois',
      coursePerformanceMetrics: 'Métriques de performance des cours',
      course: 'Cours',
      enrolled: 'Inscrit',
      completed: 'Terminé',
      completionRate: 'Taux d\'achèvement',
      avgScore: 'Score moyen',
      avgTime: 'Temps moyen',
      performanceTrends: 'Tendances de performance',
      scoreDistribution: 'Distribution des scores',
      below70: 'Moins de 70%',
      overallCompletionRate: 'Taux d\'achèvement global',
      avgTimeToComplete: 'Temps moyen d\'achèvement',
      certificatesIssued: 'Certificats délivrés',
      completionTimeline: 'Chronologie d\'achèvement',
      completionByDepartment: 'Achèvement par département',
      policeDepartments: 'Départements de police',
      educationalInstitutions: 'Institutions éducatives',
      communityOrganizations: 'Organisations communautaires',
      completionFactors: 'Facteurs d\'achèvement',
      courseDifficulty: 'Difficulté du cours',
      timeAvailability: 'Disponibilité du temps',
      supportQuality: 'Qualité du support',
      highImpact: 'Impact élevé',
      mediumImpact: 'Impact moyen',
      
      // Admin Feedback Reports
      feedbackReports: 'Rapports de commentaires',
      analyzeLearnerFeedback: 'Analyser les commentaires et métriques de satisfaction des apprenants',
      export: 'Exporter',
      satisfaction: 'Satisfaction',
      categories: 'Catégories',
      courses: 'Cours',
      avgSatisfaction: 'Satisfaction moyenne',
      fromLastMonth: 'du mois dernier',
      totalResponses: 'Total des réponses',
      responseRate: 'Taux de réponse',
      positiveSentiment: 'Sentiment positif',
      satisfactionTrend: 'Tendance de satisfaction',
      sentimentDistribution: 'Distribution des sentiments',
      positive: 'Positif',
      negative: 'Négatif',
      
      // Admin Events
      eventsManagement: 'Gestion des événements',
      createManageShareEvents: 'Créer, gérer et partager les événements à venir',
      exportCSV: 'Exporter CSV',
      createEvent: 'Créer un événement',
      searchByTitleLocation: 'Rechercher par titre ou lieu...',
      allTypes: 'Tous les types',
      reset: 'Réinitialiser',
      upcomingThisMonth: 'À venir ce mois-ci',
      totalRsvps: 'Total des RSVP',
      avgCapacityUsed: 'Capacité moyenne utilisée',
      calendar: 'Calendrier',
      viewUpcomingEventsMonthly: 'Voir les événements à venir en vue mensuelle.',
      openCalendar: 'Ouvrir le calendrier',
      manageRsvps: 'Gérer les RSVP',
      trackAttendeeResponses: 'Suivre les réponses des participants et la capacité.',
      viewRsvps: 'Voir les RSVP',
      quickAnnounce: 'Annonce rapide',
      sendQuickEventAnnouncement: 'Envoyer une annonce d\'événement rapide.',
      send: 'Envoyer',
      upcomingEvents: 'Événements à venir',
      results: 'résultat(s)',
      cybercrimeAwarenessWebinar: 'Webinaire de sensibilisation à la cybercriminalité',
      online: 'En ligne',
      attending: 'participants',
      rsvps: 'RSVP',
      share: 'Partager',
      duplicate: 'Dupliquer',
      unpublish: 'Dépublier',
      delete: 'Supprimer',
      communityOutreachBoston: 'Outreach communautaire - Boston',
      bostonMA: 'Boston, MA',
      shareLinkCopied: 'Lien de partage copié',
      linkFor: 'Lien pour',
      copiedToClipboard: 'copié dans le presse-papiers.',
      csvExported: 'CSV exporté',
      eventDataExported: 'Données d\'événement exportées avec succès.',
      youHave: 'Vous avez',
      savedEvent: 'événement enregistré',

      // Catalog & Groups
      trainingCatalog: 'Catalogue de formation',
      trainingCatalogDescription: 'Explorez notre collection complète de programmes de formation UQTR',
      searchPlaceholder: 'Rechercher par nom, description ou étiquettes...',
      courses: 'Cours',
      exploreCatalog: 'Explorer le catalogue',
      noResultsFound: 'Aucun résultat trouvé',
      noResultsDescription: 'Nous n\'avons trouvé aucun catalogue correspondant à votre recherche. Essayez d\'ajuster vos termes de recherche.',
      uqtrTrainingCatalogue: 'Catalogue de formation UQTR',
      uqtrTrainingDescription: 'Système complet de gestion de formation et de catalogue de cours',
      uqtrSelfRegistration: 'Auto-inscription UQTR',
      uqtrSelfRegistrationDescription: 'Système automatisé d\'inscription et d\'enregistrement des apprenants',
      uqtrProgressTracking: 'Suivi des progrès UQTR',
      uqtrProgressTrackingDescription: 'Outils avancés d\'analyses et de suivi des progrès',
      weeks: '12 semaines',
      intermediate: 'Intermédiaire',
      beginner: 'Débutant',
      advanced: 'Avancé',
      systemAdministration: 'Administration système',
      userManagement: 'Gestion des utilisateurs',
      enrollment: 'Inscription',
      reporting: 'Rapports',
      dataVisualization: 'Visualisation des données',
      myCommunityResources: 'Mes ressources communautaires',
      communityResourcesDescription: 'Gérez et participez à vos ressources communautaires inscrites',
      discoverGroups: 'Découvrir les groupes',
      searchMyGroups: 'Rechercher mes groupes...',
      allTypes: 'Tous les types',
      interestGroups: 'Groupes d\'intérêt',
      studyGroups: 'Groupes d\'étude',
      businessGroups: 'Groupes d\'affaires',
      members: 'Membres',
      openGroup: 'Ouvrir le groupe',
      enrolled: 'Inscrit',
      professionalTraining: 'Formation professionnelle',
      communityDevelopment: 'Développement communautaire',
      legalEducation: 'Éducation juridique',
      researchGroup: 'Groupe de recherche',
      studentOrganization: 'Organisation étudiante',
      
      // Group Detail Page
      active: 'Actif',
      trainingSessions: 'Sessions de formation',
      certifications: 'Certifications',
      groupInformation: 'Informations du groupe',
      category: 'Catégorie',
      createdDate: 'Date de création',
      lastActivity: 'Dernière activité',
      status: 'Statut',
      totalMembers: 'Total des membres',
      groupType: 'Type de groupe',
      recentActivity: 'Activité récente',
      newTrainingSession: 'Nouvelle session de formation : "Analyse des parties prenantes et évaluation des besoins"',
      newMembersJoined: '5 nouveaux officiers ont rejoint le programme de formation',
      certificationExamScheduled: 'Examen de certification du module 2 programmé pour la semaine prochaine',
      trainingMaterialsUpdated: 'Matériel de formation de conformité DOJ mis à jour',
      oneHourAgo: 'Il y a 1 heure',
      twoDaysAgo: 'Il y a 2 jours',
      fourDaysAgo: 'Il y a 4 jours',
      oneWeekAgo: 'Il y a 1 semaine',
      
      // UQTR Group Names
      uqtrLawEnforcementTraining: 'Groupe de formation en application de la loi UQTR',
      uqtrCommunityOutreach: 'Programme de sensibilisation communautaire UQTR',
      uqtrLegalTrainingSpecialists: 'Spécialistes en formation juridique UQTR',
      
      // UQTR Group Descriptions
      uqtrLawEnforcementDescription: 'Groupe de formation en application de la loi DOJ axé sur le développement professionnel, l\'analyse des parties prenantes et l\'amélioration des compétences avancées en application de la loi',
      uqtrCommunityOutreachDescription: 'Programme de développement communautaire axé sur la construction de partenariats, la promotion de l\'engagement communautaire et l\'initiative de développement social',
      uqtrLegalTrainingDescription: 'Groupe de spécialistes en éducation juridique axé sur la formation juridique avancée, les études de cas et le développement professionnel pour les professionnels du droit',
      
      // Group Categories
      lawEnforcementTraining: 'Formation en application de la loi',
      communityDevelopment: 'Développement communautaire',
      legalEducation: 'Éducation juridique',
      
      // Group Status
      activeAcceptingTrainees: 'Actif et acceptant de nouveaux stagiaires',
      activeAcceptingMembers: 'Actif et acceptant de nouveaux membres',
      activeAcceptingStudents: 'Actif et acceptant de nouveaux étudiants',
      
      // Dates
      january152024: '15 janvier 2024',
      february102024: '10 février 2024',
      march52024: '5 mars 2024',
      
      // Time References
      oneHourAgo: 'Il y a 1 heure',
      twoHoursAgo: 'Il y a 2 heures',
      threeHoursAgo: 'Il y a 3 heures',
      
      // Member Counts
      fortyFiveOfficers: '45 officiers',
      thirtyTwoMembers: '32 membres',
      twentyEightStudents: '28 étudiants',
      
      // Group Types
      professionalTrainingGroup: 'Groupe de formation professionnelle',
      communityDevelopmentGroup: 'Groupe de développement communautaire',
      legalEducationGroup: 'Groupe d\'éducation juridique',

      // Messages
      searchContacts: 'Rechercher des contacts...',
      newChat: 'Nouveau chat',
      selectContact: 'Sélectionner un contact',
      searchUsers: 'Rechercher des utilisateurs...',
      noUsersFound: 'Aucun utilisateur trouvé',
      voiceMessage: 'Message vocal',
      pdfDocument: 'Document PDF',
      addImages: 'Ajouter des images',
      addFiles: 'Ajouter des fichiers',
      typeMessage: 'Tapez un message...',
      emojis: 'Emojis',
      selectConversation: 'Sélectionnez une conversation pour commencer à envoyer des messages',
      selectConversationDescription: 'Choisissez parmi vos conversations existantes ou commencez-en une nouvelle pour vous connecter avec votre communauté d\'apprentissage',

      // Contact Names
      sarahWilson: 'Sarah Wilson',
      michaelChen: 'Michael Chen',
      emilyBrown: 'Emily Brown',
      davidKim: 'David Kim',
      jessicaTaylor: 'Jessica Taylor',
      robertJohnson: 'Robert Johnson',

      // Contact Messages
      heyThere: 'Salut !',
      letsCatchUpLater: 'Rattrapons-nous plus tard',
      didYouSeeNewCourse: 'As-tu vu le nouveau cours ?',
      thanksForHelp: 'Merci pour ton aide !',
      areYouFreeTomorrow: 'Es-tu libre demain ?',
      illGetBackToYou: 'Je te recontacte',

      // Sample Chat Messages
      hiHowAreYou: 'Salut ! Comment vas-tu ?',
      imDoingGreat: 'Je vais très bien ! Je viens de terminer le module React.',
      thatsAwesome: 'C\'est génial ! Je travaille encore dessus.',
      letMeKnowIfYouNeedHelp: 'Fais-moi savoir si tu as besoin d\'aide.',

      // Time References
      yesterday: 'Hier',
      twoDaysAgo: 'Il y a 2 jours',

      // Events
      uqtrTrainingWorkshop: 'Atelier de formation UQTR',
      uqtrCommunityOutreach: 'Outreach communautaire UQTR',
      uqtrPolicyRoundtable: 'Table ronde politique UQTR',
      online: 'En ligne',
      troisRivieres: 'Trois-Rivières, QC',
      uqtrCampus: 'Campus UQTR',
      webinar: 'Webinaire',
      outreach: 'Outreach',
      meeting: 'Réunion',
      discoverAndRsvp: 'Découvrez et répondez aux événements à venir.',
      myRsvps: 'Mes RSVP',
      searchByTitleOrLocation: 'Rechercher par titre ou lieu...',
      filterByType: 'Filtrer par type',
      reset: 'Réinitialiser',
      upcomingThisMonth: 'À venir ce mois-ci',
      totalRsvps: 'Total des RSVP',
      avgCapacityUsed: 'Capacité moyenne utilisée',
      viewUpcomingEvents: 'Voir les événements à venir en vue mensuelle.',
      openCalendar: 'Ouvrir le calendrier',
      seeEventsResponded: 'Voir les événements auxquels vous avez répondu.',
      viewRsvps: 'Voir les RSVP',
      subscribe: 'S\'abonner',
      getEventReminders: 'Recevez des rappels et des mises à jour d\'événements.',
      unsubscribe: 'Se désabonner',
      upcomingEvents: 'Événements à venir',
      results: 'résultat(s)',
      attending: 'participants',
      updateRsvp: 'Mettre à jour RSVP',
      rsvp: 'RSVP',
      rsvpTo: 'RSVP pour',
      interested: 'Intéressé',
      notGoing: 'Ne participe pas',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      saved: 'Enregistré',
      save: 'Enregistrer',
      addToCalendar: 'Ajouter au calendrier',
      share: 'Partager',
      youHave: 'Vous avez',
      savedEvent: 'événement enregistré',
      subscribed: 'Abonné',
      unsubscribed: 'Désabonné',
      willReceiveReminders: 'Vous recevrez des rappels pour les événements à venir.',
      willNotReceiveReminders: 'Vous ne recevrez plus de rappels.',
      rsvpUpdated: 'RSVP mis à jour',
      for: 'pour',
      addedToCalendar: 'Ajouté au calendrier',
      icsFileDownloaded: 'Fichier ICS téléchargé.',
      shareLinkCopied: 'Lien de partage copié',
      linkFor: 'Lien pour',
      copiedToClipboard: 'copié dans le presse-papiers.',

      // Evaluation & Feedback
      evaluationFeedback: 'Évaluation et commentaires',
      monitorLearningProgress: 'Surveillez vos progrès d\'apprentissage et l\'efficacité de la formation.',
      postTrainingSurveys: 'Enquêtes post-formation',
      shareTrainingExperience: 'Partagez votre expérience de formation',
      takeSurvey: 'Répondre à l\'enquête',
      selfAssessment: 'Auto-évaluation',
      evaluateSkillsProgress: 'Évaluez vos compétences et vos progrès',
      startAssessment: 'Commencer l\'évaluation',
      surveyCompletion: 'Achèvement de l\'enquête',
      averageRating: 'Note moyenne',
      totalResponses: 'Total des réponses',
      overallScore: 'Score global',
      skillAssessment: 'Évaluation des compétences',
      recentFeedback: 'Commentaires récents',
      excellentCourseContent: 'Excellent contenu de cours et exemples pratiques.',
      veryHelpfulUnderstanding: 'Très utile pour comprendre les besoins des étudiants.',
      outstandingProgramRealWorld: 'Programme exceptionnel avec des applications du monde réel.',
      communicationSkills: 'Compétences en communication',
      technicalKnowledge: 'Connaissances techniques',
      leadershipSkills: 'Compétences en leadership',
      problemSolving: 'Résolution de problèmes',

      // Help & Support
      frequentlyAskedQuestions: 'Foire aux questions',
      findAnswersCommonQuestions: 'Trouvez des réponses aux questions courantes sur notre plateforme',
      generalQuestions: 'Questions générales',
      howToResetPassword: 'Comment réinitialiser mon mot de passe ?',
      resetPasswordAnswer: 'Pour réinitialiser votre mot de passe, cliquez sur le lien "Mot de passe oublié" sur la page de connexion et suivez les instructions envoyées à votre courriel.',
      howToUpdateProfile: 'Comment mettre à jour mes informations de profil ?',
      updateProfileAnswer: 'Vous pouvez mettre à jour vos informations de profil en cliquant sur votre photo de profil dans le coin supérieur droit et en sélectionnant "Modifier le profil".',
      systemRequirements: 'Quelles sont les exigences du système ?',
      systemRequirementsAnswer: 'Notre plateforme fonctionne mieux sur les dernières versions de Chrome, Firefox, Safari et Edge. Assurez-vous que JavaScript est activé.',
      howToContactSupport: 'Comment contacter le support ?',
      contactSupportAnswer: 'Vous pouvez contacter notre équipe de support via la page Contact Support ou en envoyant un courriel à support@uqtr.ca',
      mobileAppAvailable: 'Y a-t-il une application mobile disponible ?',
      mobileAppAnswer: 'Oui, notre application mobile est disponible pour les appareils iOS et Android. Vous pouvez la télécharger depuis l\'App Store ou Google Play Store.',
      wereHereToHelp: 'Nous sommes là pour vous aider ! Contactez notre équipe de support pour obtenir de l\'aide.',
      contactInformation: 'Informations de contact',
      emailUs: 'Envoyez-nous un courriel',
      callUs: 'Appelez-nous',
      workingHours: 'Heures de travail',
      mondayFridayHours: 'Lundi - Vendredi : 9h00 - 18h00',
      sendUsMessage: 'Envoyez-nous un message',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Jean Dupont',
      emailPlaceholder: 'jean@uqtr.ca',
      subjectPlaceholder: 'De quoi s\'agit-il ?',
      messagePlaceholder: 'Comment pouvons-nous vous aider ?',
      sendMessage: 'Envoyer le message',
      resetPasswordSimpleAnswer: 'Vous pouvez réinitialiser votre mot de passe en cliquant sur "Mot de passe oublié" sur la page de connexion.',
      updateProfileSimpleAnswer: 'Naviguez vers les paramètres de votre profil pour mettre à jour vos informations personnelles.',
      userGuidesDocumentation: 'Guides utilisateur et documentation',
      findHelpfulGuides: 'Trouvez des guides utiles, des tutoriels et de la documentation pour tirer le meilleur parti de notre plateforme.',
      gettingStartedGuide: 'Guide de démarrage',
      gettingStartedDescription: 'Apprenez à configurer votre compte et à naviguer sur la plateforme avec notre guide complet.',
      videoTutorials: 'Tutoriels vidéo',
      videoTutorialsDescription: 'Regardez des tutoriels vidéo étape par étape pour maîtriser toutes les fonctionnalités de notre plateforme.',
      apiDocumentation: 'Documentation API',
      apiDocumentationDescription: 'Documentation technique pour l\'intégration avec notre API et la création de solutions personnalisées.',
      keyboardShortcuts: 'Raccourcis clavier',
      keyboardShortcutsDescription: 'Augmentez votre productivité avec ces raccourcis clavier pratiques pour les actions courantes.',
      videoSeries: 'Série vidéo',
      web: 'Web',
      cheatSheet: 'Aide-mémoire',
      allGuides: 'Tous les guides',
      gettingStarted: 'Démarrage',
      features: 'Fonctionnalités',
      troubleshooting: 'Dépannage',
      viewGuide: 'Voir le guide',
      lastUpdated: 'Dernière mise à jour',
      cantFindWhatLookingFor: 'Vous ne trouvez pas ce que vous cherchez ?',
      supportTeamReadyToHelp: 'Notre équipe de support est toujours prête à vous aider avec toutes vos questions.',
      createSupportTicket: 'Créer un ticket de support',
      fillOutFormSubmitTicket: 'Remplissez le formulaire ci-dessous pour soumettre un ticket de support à notre équipe.',
      newSupportTicket: 'Nouveau ticket de support',
      brieflyDescribeIssue: 'Décrivez brièvement votre problème',
      selectPriority: 'Sélectionner la priorité',
      low: 'Faible',
      medium: 'Moyen',
      high: 'Élevé',
      urgent: 'Urgent',
      selectCategory: 'Sélectionner la catégorie',
      technicalIssue: 'Problème technique',
      billing: 'Facturation',
      account: 'Compte',
      featureRequest: 'Demande de fonctionnalité',
      other: 'Autre',
      provideDetailedInformation: 'Veuillez fournir des informations détaillées sur votre problème',
      attachments: 'Pièces jointes',
      addFiles: 'Ajouter des fichiers',
      filesAttached: 'fichier(s) joint(s)',
      submitTicket: 'Soumettre le ticket',

      // Task Management
      taskManagement: 'Gestion des tâches',
      organizeTrackTasksEfficiently: 'Organisez et suivez vos tâches efficacement',
      backToHome: 'Retour à l\'accueil',
      addNewTask: 'Ajouter une nouvelle tâche',
      createNewTask: 'Créer une nouvelle tâche',
      editTask: 'Modifier la tâche',
      taskTitle: 'Titre de la tâche',
      taskDescription: 'Description de la tâche',
      deadline: 'Échéance',
      deadlinePlaceholder: 'Échéance (ex: Aujourd\'hui, Demain, La semaine prochaine)',
      priority: 'Priorité',
      status: 'Statut',
      category: 'Catégorie',
      addTask: 'Ajouter la tâche',
      updateTask: 'Mettre à jour la tâche',
      cancel: 'Annuler',
      allTasks: 'Toutes les tâches',
      pleaseFillRequiredFields: 'Veuillez remplir tous les champs requis',
      taskAddedSuccessfully: 'Tâche ajoutée avec succès',
      taskUpdatedSuccessfully: 'Tâche mise à jour avec succès',
      taskDeletedSuccessfully: 'Tâche supprimée avec succès',
      taskMarkedAsPending: 'Tâche marquée comme en attente',
      taskCompleted: 'Tâche terminée',
      highPriority: 'Priorité élevée',
      mediumPriority: 'Priorité moyenne',
      lowPriority: 'Priorité faible',
      pending: 'En attente',
      inprogress: 'En cours',
      completed: 'Terminé',
      courseDevelopment: 'Développement de cours',
      assessment: 'Évaluation',
      contentUpdates: 'Mises à jour de contenu',
      administration: 'Administration',
      compliance: 'Conformité',
      trainingDelivery: 'Livraison de formation',
      today: 'Aujourd\'hui',
      tomorrow: 'Demain',
      nextWeek: 'La semaine prochaine',
      inTwoWeeks: 'Dans 2 semaines',
      nextMonth: 'Le mois prochain',
      thisFriday: 'Ce vendredi',
      reviewUQTRTrainingCatalogue: 'Examiner le contenu du catalogue de formation UQTR',
      reviewUQTRTrainingCatalogueDescription: 'Examiner et mettre à jour le contenu du catalogue de formation UQTR pour la précision et la conformité aux normes universitaires',
      gradeUQTRSelfRegistration: 'Noter les évaluations d\'auto-inscription UQTR',
      gradeUQTRSelfRegistrationDescription: 'Évaluer les récentes évaluations du système d\'auto-inscription UQTR et fournir des commentaires détaillés aux participants',
      prepareUQTRProgressTracking: 'Préparer l\'examen de suivi des progrès UQTR',
      prepareUQTRProgressTrackingDescription: 'Créer des questions d\'examen complètes pour l\'évaluation finale du module de suivi des progrès UQTR',
      updateUQTRComplianceMaterials: 'Mettre à jour les matériaux de formation de conformité UQTR',
      updateUQTRComplianceMaterialsDescription: 'Mettre à jour les matériaux de formation de conformité UQTR avec les dernières exigences réglementaires universitaires',
      scheduleUQTRInstructorSessions: 'Programmer les sessions d\'instructeurs UQTR',
      scheduleUQTRInstructorSessionsDescription: 'Établir l\'horaire de formation pour les instructeurs de faculté, d\'éducation et de développement étudiant UQTR',
      reviewUQTRStakeholderAnalysis: 'Examiner le module d\'analyse des parties prenantes UQTR',
      reviewUQTRStakeholderAnalysisDescription: 'Examen final du contenu du module d\'analyse des parties prenantes et d\'évaluation des besoins UQTR avant publication',

      // Today's Task Section
      todaysTask: 'Tâche d\'aujourd\'hui',
      newTask: 'Nouvelle tâche',
      viewAllTasks: 'Voir toutes les tâches',
      all: 'Toutes',
      open: 'Ouvertes',
      closed: 'Fermées',
      archived: 'Archivées',
      completeUQTRTrainingCatalogue: 'Compléter le catalogue de formation UQTR',
      completeUQTRTrainingCatalogueDescription: 'Fondements du système de catalogue de formation UQTR',
      reviewUQTRSelfRegistration: 'Examiner l\'auto-inscription UQTR',
      reviewUQTRSelfRegistrationDescription: 'Apprentissage professionnel dans l\'auto-inscription UQTR',
      submitUQTRProgressTracking: 'Soumettre le suivi des progrès UQTR',
      submitUQTRProgressTrackingDescription: 'Évaluation des besoins dans le suivi des progrès UQTR',

      // My Courses Section
      myCourses: 'Mes cours',
      viewAll: 'Voir tout',
      modules: 'modules',
      students: 'étudiants',
      uqtrUniversity: 'Université UQTR',
      buildingExcellenceFosteringGrowth: 'Construire l\'excellence, favoriser la croissance',
      progress: 'Progrès'
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
